module Games
  module Dikkenek
    class Data
      include ActiveModel::Model

      CHARACTERS = [ "JC", "Stef", "Greg", "Nadine", "Claudy", "Natasha", "Sylvie", "Daisy",
                    "Laurence", "Aziz", "Evelyne", "Fabienne", "Baudouin", "Autre" ].freeze

      QUOTES = [
                { quote: "Qu'est-ce qui ne va pas encore ? Le grand amour, c'est ça ? Et tu veux pas commencer avec un petit amour... tout de suite le grand !",
                author: "JC", scene: 1, difficulty: 2 },
                { quote: "Avant la fin de la semaine, je te trouve une gonzesse. T'auras plus qu'à te pencher... ça tu sais faire tout seul.",
                author: "JC", scene: 1, difficulty: 2 },
                { quote: "On est tombé sur une cinglée... un cas clinique désespéré.",
                author: "JC", scene: 1, difficulty: 3 },
                { quote: "On va peut-être pas mettre la barre trop haut, d'accord ?",
                author: "JC", scene: 1, difficulty: 3 },
                { quote: "Quoique se taper une moche, c'est pas ce qu'il y a de plus simple. Elles sont terriblement méfiantes, les laides, tu vois ? Les laides.",
                author: "JC", scene: 1, difficulty: 2 },
                { quote: "On va attaquer la middle-class. Avant la fin de la semaine, tu rencontres la femme de ta vie !",
                author: "JC", scene: 1, difficulty: 2 },
                { quote: "Ouais dis, Monique, c'est moi. Dis, tu vas me rendre un service. Annule-moi un peu ce rendez-vous avec ces deux imbéciles de l'école de TV, là.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "J'ai pas le temps de faire ça... j'ai matériellement pas le temps de faire ça.",
                author: "Claudy", scene: 2, difficulty: 3 },
                { quote: "Des trous de culs pareils, ça m'intéresse pas.",
                author: "Claudy", scene: 2, difficulty: 4 },
                { quote: "I.A.D. ? Connais pas, inconnu au bataillon, jamais entendu.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "Bon, c'est pour le fameux travail de fin d'études, là ?",
                author: "Claudy", scene: 2, difficulty: 3 },
                { quote: "Ça doit durer combien de temps ? sept-huit minutes ?",
                author: "Claudy", scene: 2, difficulty: 5 },
                { quote: "Bon on va y aller, hein. Je suis prêt. Vous dites pas 'Action!' ? Dites, fieux, eh ! oh !",
                author: "Claudy", scene: 2, difficulty: 3 },
                { quote: "je dis ça parce que je regardais ton objectif. C'est du digital, hein ? Du trente-cinq millimètres ?",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "En fait, je suis photographe de... je fais des photos de charme, en somme. Mais c'est un peu hors-contexte.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "je suis Directeur and Sales Marketing-Manager des Abattoirs d'Anderlecht.",
                author: "Claudy", scene: 2, difficulty: 1 },
                { quote: "Quand les bêtes arrivent, elles sont cent-cinquante dans un camion. Pourquoi cent-cinquante ? De façon à ne pas trébucher pendant le transport.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "Une fois qu'elles arrivent ici, c'est pas compliqué, elles suivent la ligne blanche, et on les dirige inéluctablement,
                          elles sont deux par deux, vers la zone d'abattage. c'est peut-être la partie la moins marrante, quoique.",
                author: "Claudy", scene: 2, difficulty: 3 },
                { quote: "on a jamais dû tirer deux fois, si vous voulez... si vous voyez ce que je veux dire.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "enfin moi c'est mon petit pêché mignon.",
                author: "Claudy", scene: 2, difficulty: 5 },
                { quote: "Une fois que la bête est décédée, elle se dirige... enfin on la dirige, étant donné qu'elle ne marche plus...",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "Ecoute fieu, tu commences par me faire chier avec ta torche, hein ? Ça fait depuis le début que tu m'emmerdes.
                          Tu m'as déjà fourré la gueule là-bas. Ça va suffire maintenant ?",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "J'ai l'impression qu'on m'a donné les deux clowns de l'I.A.D. là, le fond du panier.",
                author: "Claudy", scene: 2, difficulty: 1 },
                { quote: "J'allais y venir. Chaque chose arrive en son temps. Tu vas pas me dire toi ce que je dois raconter.",
                author: "Claudy", scene: 2, difficulty: 3 },
                { quote: "Faut savoir que sur une bête de sept-cents kilos, il y a trois-cent-cinquante kilos qui sont considérés comme matières
                          ou restes impropres à la consommation.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "Je veux dire par la que vous verrez jamais dans une boucherie des narines, un scrotum, un anus ou euh... des intestins par exemple.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "Les intestins, ce n'est jamais que de l'herbe digérée. On appelle ça plus communément de la merde, pour votre information.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "On racle tout ça, on tape tout dans des grandes bassines... nous autres on appelle ça des piscines.",
                author: "Claudy", scene: 2, difficulty: 3 },
                { quote: "enfin, ça c'est notre petite popote, c'est le pot belge comme on dit.",
                author: "Claudy", scene: 2, difficulty: 4 },
                { quote: "C'est compris ? Un beau matin, vous allez aussi vous retrouver dans une cuve.",
                author: "Claudy", scene: 2, difficulty: 5 },
                { quote: "Tchao Polak ! Fais-moi un grand paquet de frites avec sauce, s'il te plait.",
                author: "Aziz", scene: 3, difficulty: 3 },
                { quote: "Euh... je sais pas moi... sauce Dallas. Mets-moi la sauce à part. Et trois boulettes avec.",
                author: "Aziz", scene: 3, difficulty: 2 },
                { quote: "Omar ! La sauce à part ou sur les frites ?",
                author: "Aziz", scene: 3, difficulty: 3 },
                { quote: "Sur les boulettes ! Et tu mets six, sept fricadelles aussi.",
                author: "Autre", scene: 3, difficulty: 4 },
                { quote: "Dix bières s'il vous plait ? Dix Vedett.",
                author: "Stef", scene: 3, difficulty: 4 },
                { quote: "Comment il est à l'aise, lui. T'es aveugle ou quoi ? J'étais juste en train de commander des Bicky.
                          Tu joues avec ta vie, toi.",
                author: "Aziz", scene: 3, difficulty: 2 },
                { quote: "Qu'est-ce qu'il a ce fils de pute ? Allez viens !",
                author: "Aziz", scene: 3, difficulty: 5 },
                { quote: "Le type y vient à l'aise, s'excuse même pas, il me dépasse... t'es poli ou t'es pas poli, toi ?",
                author: "Aziz", scene: 3, difficulty: 1 },
                { quote: "T'es pas en classe verte, toi ? Il me semblait bien que c'était toi ! Avec ton vieil accent de chanteur de rap, là... Hip-hop.",
                author: "JC", scene: 3, difficulty: 2 },
                { quote: "Et cette manie que tu as de cracher partout comme un lama. C'est excessivement énervant.",
                author: "JC", scene: 3, difficulty: 2 },
                { quote: "C'est mon pote. Et tu lui parles autrement ! Excuses-toi. Excuses-toi tout de suite !",
                author: "JC", scene: 3, difficulty: 3 },
                { quote: "Tu sais ce qu'il y a dans une fricadelle ? Hein ? J'ai vu un reportage là-dessus.",
                author: "JC", scene: 3, difficulty: 4 },
                { quote: "Ah, ça du porc, c'est sûr il y en a pas, hein. Mais tu donnes ça à un chien, il le bouffe pas non plus.",
                author: "JC", scene: 3, difficulty: 3 },
                { quote: "Dis, je peux te poser une question ? Le prend pas mal, mais qu'est-ce que tu comptes faire, toi, pour la rentrée ?",
                author: "Sylvie", scene: 4, difficulty: 2 },
                { quote: "Tu peux pas continuer comme ça à échouer tous les ans. C'est échec sur échec.",
                author: "Sylvie", scene: 4, difficulty: 5 },
                { quote: "Alors ça, guindailler, la grasse matinée, ça, ça va, ça. Ça tu sais faire.",
                author: "Sylvie", scene: 4, difficulty: 4 },
                { quote: "si moi aujourd'hui, je suis au chômage, c'est quand même pas de ma faute. Moi j'avais rien demandé, à dix-sept ans... rien.",
                author: "Sylvie", scene: 4, difficulty: 3 },
                { quote: "Moi je voulais faire le barreau, moi. Pas faire des moutards avec l'autre con, là.",
                author: "Sylvie", scene: 4, difficulty: 2 },
                { quote: "Moi, je voulais devenir... une grande psychologue, tu vois ? Aider les gens, rendre service, M.S.F., tout le bordel.",
                author: "Sylvie", scene: 4, difficulty: 3 },
                { quote: "Et quand tes parents sont morts, ma vie aussi elle a changé.",
                author: "Sylvie", scene: 4, difficulty: 4 },
                { quote: "Eh, bah eh, le jour de l'enterrement, il a fallu que je devienne maman, moi... d'un coup. Bonjour !",
                author: "Sylvie", scene: 4, difficulty: 2 },
                { quote: "Finalement c'est un peu ça le but dans la vie, non ? Réussir à rien foutre.",
                author: "Natasha", scene: 4, difficulty: 2 },
                { quote: "Dis-donc toi, goulaf ! Tu sais pas lire ? C'est interdit de manger dans les musées !",
                author: "Nadine", scene: 5, difficulty: 3 },
                { quote: "Comme quoi, on ne le dira jamais assez : la ceinture ! Un petit clic vaut mieux qu'une grande claque !",
                author: "Nadine", scene: 5, difficulty: 2 },
                { quote: "Alors les enfants ? Qui veut jouer au mort ? Qui a déjà eu un accident de voiture ici ? Toi ? Toi ? Toi ? Personne ? Eh ben ça va venir, alors.",
                author: "Nadine", scene: 5, difficulty: 2 },
                { quote: "A 18 ans on commence à boire... et puis on veut impressionner ses amis. Et paf ! C'est le platane assuré en revenant de Louvain-la-Neuve.",
                author: "Nadine", scene: 5, difficulty: 3 },
                { quote: "Toi Charlotte, tu sais ce que c'est qu'un pare-brise, hein ? Eh oui !",
                author: "Nadine", scene: 5, difficulty: 3 },
                { quote: "Si aujourd'hui tu ressembles plus à Albator qu'à Candy, c'est parce que ta maman, elle flûte !",
                author: "Nadine", scene: 5, difficulty: 2 },
                { quote: "Elle est jolie cette grille, non ? Vous savez que le type a eu cent trente-sept fractures ?",
                author: "Nadine", scene: 5, difficulty: 3 },
                { quote: "Aaaaahaha ! Elle est morte la maîtresse !",
                author: "Nadine", scene: 5, difficulty: 1 },
                { quote: "Maintenant, nous allons faire une minute de silence pour tous ces gens qui sont derrière moi.",
                author: "Nadine", scene: 5, difficulty: 3 },
                { quote: "A la boutique cette semaine, le t-shirt de nos plus grands accidentés de la route... Lady Di... Ayrton Senna...",
                author: "Autre", scene: 5, difficulty: 3 },
                { quote: "Eh ben, ça roucoule ici, hein ? C'est un cinéma porno ou quoi ?",
                author: "JC", scene: 6, difficulty: 3 },
                { quote: "D'identité sexuelle... ça veut strictement rien dire, ou alors faut qu'on m'explique.",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "Des gros nénés... un gros ventre... des grosses cuisses... ça change, hein ? Ben oui ! Ça change des magazines...",
                author: "Autre", scene: 6, difficulty: 2 },
                { quote: "Ma main à couper que ça va encore tourner autour du trou de balle, cette histoire...",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "Qu'est-ce qu'il a celui-là, on se connait ?",
                author: "JC", scene: 6, difficulty: 5 },
                { quote: "Comment je sais que c'est toi, ben... je vois ton nom qui clignote sur l'écran, tiens. T'es vraiment con...",
                author: "Greg", scene: 6, difficulty: 3 },
                { quote: "Excuse-moi... oho... excuse-moi... ça te dérangerait pas de sortir pour aller téléphoner ?",
                author: "Stef", scene: 6, difficulty: 4 },
                { quote: "Ta gueule ! Je parle, là.",
                author: "Greg", scene: 6, difficulty: 4 },
                { quote: "Non, c'est pas à toi que je parle. Non, c'est à un crétin, là. Un mongol.",
                author: "Greg", scene: 6, difficulty: 3 },
                { quote: "Tu sors pour téléphoner ou alors t'éteins ton téléphone.",
                author: "Stef", scene: 6, difficulty: 3 },
                { quote: "Eh, achètes des cotons-tige alors, il te demande pour la deuxième et la dernière fois si tu peux pas sortir pour téléphoner à ta pouffiasse !",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "Tu veux te battre, c'est ça ? Vas-y connard !",
                author: "Greg", scene: 6, difficulty: 3 },
                { quote: "Il est tout à fait fou ce type...",
                author: "JC", scene: 6, difficulty: 3 },
                { quote: "Au cinéma tu restes debout, toi ? Assiez-toi ! Et regardes seulement devant toi.",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "Non mais t'as vu ça madame ? T'as vu comment il me parle ?",
                author: "JC", scene: 6, difficulty: 3 },
                { quote: "Non c'est rien, c'est un crétin, là...",
                author: "Greg", scene: 6, difficulty: 5 },
                { quote: "Mais ce type le fait exprès, tsé !",
                author: "JC", scene: 6, difficulty: 4 },
                { quote: "Mais non, c'est pas à toi que je parle, mais tu comprends jamais rien, t'es vraiment conne !",
                author: "Greg", scene: 6, difficulty: 2 },
                { quote: "La première c'est pour te faire la leçon, petit con ! La deuxième c'est pour le principe !
                          La troisième c'est parce que jamais deux sans trois !",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "Qu'est-ce que vous faites le quinze août ? Non c'est parce que... je fête mes dix-huit ans.",
                author: "Fabienne", scene: 6, difficulty: 2 },
                { quote: "J'organise une petite fête au Zoute. Ça va être bien, j'invite toute la Belgique...",
                author: "Fabienne", scene: 6, difficulty: 3 },
                { quote: "C'est quoi cette tutte ? Elle a aussi été bercée trop près du mur, celle-là ?",
                author: "JC", scene: 6, difficulty: 3 },
                { quote: "Tiens ! De la part du bébé manager. Encore une petite ? Oh elle a dû faire mal, celle-là.",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "",
                author: "JC", scene: 7, difficulty: 3 },
                { quote: "",
                author: "JC", scene: 7, difficulty: 3 },
                { quote: "",
                author: "JC", scene: 7, difficulty: 3 },
                { quote: "",
                author: "JC", scene: 7, difficulty: 3 }
              ].freeze
    end
  end
end
