module Games
  module Dikkeneks
    class Data
      include ActiveModel::Model

      CHARACTERS = [ "JC", "Stef", "Greg", "Nadine", "Claudy", "Natasha", "Sylvie", "Daisy",
                    "Laurence", "Aziz", "Evelyne", "Fabienne", "Baudouin", "Autre" ].freeze

      QUOTES = [
                { quote: "Qu'est-ce qui ne va pas encore ? Le grand amour, c'est ça ? Et tu veux pas commencer avec un petit amour... tout de suite le grand !",
                author: "JC", scene: 1, difficulty: 2 },
                { quote: "Avant la fin de la semaine, je te trouve une gonzesse. T'auras plus qu'à te pencher... ça tu sais faire tout seul.",
                author: "JC", scene: 1, difficulty: 2 },
                { quote: "On est tombé sur une cinglée... un cas clinique désespéré.",
                author: "JC", scene: 1, difficulty: 3 },
                { quote: "On va peut-être pas mettre la barre trop haut, d'accord ?",
                author: "JC", scene: 1, difficulty: 3 },
                { quote: "Quoique se taper une moche, c'est pas ce qu'il y a de plus simple. Elles sont terriblement méfiantes, les laides, tu vois ? Les laides.",
                author: "JC", scene: 1, difficulty: 2 },
                { quote: "On va attaquer la middle-class. Avant la fin de la semaine, tu rencontres la femme de ta vie !",
                author: "JC", scene: 1, difficulty: 2 },
                { quote: "Ouais dis, Monique, c'est moi. Dis, tu vas me rendre un service. Annule-moi un peu ce rendez-vous avec ces deux imbéciles de l'école de TV, là.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "J'ai pas le temps de faire ça... j'ai matériellement pas le temps de faire ça.",
                author: "Claudy", scene: 2, difficulty: 3 },
                { quote: "Des trous de culs pareils, ça m'intéresse pas.",
                author: "Claudy", scene: 2, difficulty: 4 },
                { quote: "I.A.D. ? Connais pas, inconnu au bataillon, jamais entendu.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "Bon, c'est pour le fameux travail de fin d'études, là ?",
                author: "Claudy", scene: 2, difficulty: 3 },
                { quote: "Ça doit durer combien de temps ? sept-huit minutes ?",
                author: "Claudy", scene: 2, difficulty: 5 },
                { quote: "Bon on va y aller, hein. Je suis prêt. Vous dites pas 'Action!' ? Dites, fieux, eh ! oh !",
                author: "Claudy", scene: 2, difficulty: 3 },
                { quote: "je dis ça parce que je regardais ton objectif. C'est du digital, hein ? Du trente-cinq millimètres ?",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "En fait, je suis photographe de... je fais des photos de charme, en somme. Mais c'est un peu hors-contexte.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "je suis Directeur and Sales Marketing-Manager des Abattoirs d'Anderlecht.",
                author: "Claudy", scene: 2, difficulty: 1 },
                { quote: "Quand les bêtes arrivent, elles sont cent-cinquante dans un camion. Pourquoi cent-cinquante ? De façon à ne pas trébucher pendant le transport.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "Une fois qu'elles arrivent ici, c'est pas compliqué, elles suivent la ligne blanche, et on les dirige inéluctablement, elles sont deux par deux, vers la zone d'abattage. c'est peut-être la partie la moins marrante, quoique.",
                author: "Claudy", scene: 2, difficulty: 3 },
                { quote: "on a jamais dû tirer deux fois, si vous voulez... si vous voyez ce que je veux dire.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "enfin moi c'est mon petit pêché mignon.",
                author: "Claudy", scene: 2, difficulty: 5 },
                { quote: "Une fois que la bête est décédée, elle se dirige... enfin on la dirige, étant donné qu'elle ne marche plus...",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "Ecoute fieu, tu commences par me faire chier avec ta torche, hein ? Ça fait depuis le début que tu m'emmerdes. Tu m'as déjà fourré la gueule là-bas. Ça va suffire maintenant ?",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "J'ai l'impression qu'on m'a donné les deux clowns de l'I.A.D. là, le fond du panier.",
                author: "Claudy", scene: 2, difficulty: 1 },
                { quote: "J'allais y venir. Chaque chose arrive en son temps. Tu vas pas me dire toi ce que je dois raconter.",
                author: "Claudy", scene: 2, difficulty: 3 },
                { quote: "Faut savoir que sur une bête de sept-cents kilos, il y a trois-cent-cinquante kilos qui sont considérés comme matières ou restes impropres à la consommation.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "Je veux dire par la que vous verrez jamais dans une boucherie des narines, un scrotum, un anus ou euh... des intestins par exemple.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "Les intestins, ce n'est jamais que de l'herbe digérée. On appelle ça plus communément de la merde, pour votre information.",
                author: "Claudy", scene: 2, difficulty: 2 },
                { quote: "On racle tout ça, on tape tout dans des grandes bassines... nous autres on appelle ça des piscines.",
                author: "Claudy", scene: 2, difficulty: 3 },
                { quote: "enfin, ça c'est notre petite popote, c'est le pot belge comme on dit.",
                author: "Claudy", scene: 2, difficulty: 4 },
                { quote: "C'est compris ? Un beau matin, vous allez aussi vous retrouver dans une cuve.",
                author: "Claudy", scene: 2, difficulty: 5 },
                { quote: "Tchao Polak ! Fais-moi un grand paquet de frites avec sauce, s'il te plait.",
                author: "Aziz", scene: 3, difficulty: 3 },
                { quote: "Euh... je sais pas moi... sauce Dallas. Mets-moi la sauce à part. Et trois boulettes avec.",
                author: "Aziz", scene: 3, difficulty: 2 },
                { quote: "Omar ! La sauce à part ou sur les frites ?",
                author: "Aziz", scene: 3, difficulty: 3 },
                { quote: "Sur les boulettes ! Et tu mets six, sept fricadelles aussi.",
                author: "Autre", scene: 3, difficulty: 4 },
                { quote: "Dix bières s'il vous plait ? Dix Vedett.",
                author: "Stef", scene: 3, difficulty: 4 },
                { quote: "Comment il est à l'aise, lui. T'es aveugle ou quoi ? J'étais juste en train de commander des Bicky. Tu joues avec ta vie, toi.",
                author: "Aziz", scene: 3, difficulty: 2 },
                { quote: "Qu'est-ce qu'il a ce fils de pute ? Allez viens !",
                author: "Aziz", scene: 3, difficulty: 5 },
                { quote: "Le type y vient à l'aise, s'excuse même pas, il me dépasse... t'es poli ou t'es pas poli, toi ?",
                author: "Aziz", scene: 3, difficulty: 1 },
                { quote: "T'es pas en classe verte, toi ? Il me semblait bien que c'était toi ! Avec ton vieil accent de chanteur de rap, là... Hip-hop.",
                author: "JC", scene: 3, difficulty: 2 },
                { quote: "Et cette manie que tu as de cracher partout comme un lama. C'est excessivement énervant.",
                author: "JC", scene: 3, difficulty: 2 },
                { quote: "C'est mon pote. Et tu lui parles autrement ! Excuses-toi. Excuses-toi tout de suite !",
                author: "JC", scene: 3, difficulty: 3 },
                { quote: "Tu sais ce qu'il y a dans une fricadelle ? Hein ? J'ai vu un reportage là-dessus.",
                author: "JC", scene: 3, difficulty: 4 },
                { quote: "Ah, ça du porc, c'est sûr il y en a pas, hein. Mais tu donnes ça à un chien, il le bouffe pas non plus.",
                author: "JC", scene: 3, difficulty: 3 },
                { quote: "Dis, je peux te poser une question ? Le prend pas mal, mais qu'est-ce que tu comptes faire, toi, pour la rentrée ?",
                author: "Sylvie", scene: 4, difficulty: 2 },
                { quote: "Tu peux pas continuer comme ça à échouer tous les ans. C'est échec sur échec.",
                author: "Sylvie", scene: 4, difficulty: 5 },
                { quote: "Alors ça, guindailler, la grasse matinée, ça, ça va, ça. Ça tu sais faire.",
                author: "Sylvie", scene: 4, difficulty: 4 },
                { quote: "si moi aujourd'hui, je suis au chômage, c'est quand même pas de ma faute. Moi j'avais rien demandé, à dix-sept ans... rien.",
                author: "Sylvie", scene: 4, difficulty: 3 },
                { quote: "Moi je voulais faire le barreau, moi. Pas faire des moutards avec l'autre con, là.",
                author: "Sylvie", scene: 4, difficulty: 2 },
                { quote: "Moi, je voulais devenir... une grande psychologue, tu vois ? Aider les gens, rendre service, M.S.F., tout le bordel.",
                author: "Sylvie", scene: 4, difficulty: 3 },
                { quote: "Et quand tes parents sont morts, ma vie aussi elle a changé.",
                author: "Sylvie", scene: 4, difficulty: 4 },
                { quote: "Eh, bah eh, le jour de l'enterrement, il a fallu que je devienne maman, moi... d'un coup. Bonjour !",
                author: "Sylvie", scene: 4, difficulty: 2 },
                { quote: "Finalement c'est un peu ça le but dans la vie, non ? Réussir à rien foutre.",
                author: "Natasha", scene: 4, difficulty: 2 },
                { quote: "Dis-donc toi, goulaf ! Tu sais pas lire ? C'est interdit de manger dans les musées !",
                author: "Nadine", scene: 5, difficulty: 3 },
                { quote: "Comme quoi, on ne le dira jamais assez : la ceinture ! Un petit clic vaut mieux qu'une grande claque !",
                author: "Nadine", scene: 5, difficulty: 2 },
                { quote: "Alors les enfants ? Qui veut jouer au mort ? Qui a déjà eu un accident de voiture ici ? Toi ? Toi ? Toi ? Personne ? Eh ben ça va venir, alors.",
                author: "Nadine", scene: 5, difficulty: 2 },
                { quote: "A 18 ans on commence à boire... et puis on veut impressionner ses amis. Et paf ! C'est le platane assuré en revenant de Louvain-la-Neuve.",
                author: "Nadine", scene: 5, difficulty: 3 },
                { quote: "Toi Charlotte, tu sais ce que c'est qu'un pare-brise, hein ? Eh oui !",
                author: "Nadine", scene: 5, difficulty: 3 },
                { quote: "Si aujourd'hui tu ressembles plus à Albator qu'à Candy, c'est parce que ta maman, elle flûte !",
                author: "Nadine", scene: 5, difficulty: 2 },
                { quote: "Elle est jolie cette grille, non ? Vous savez que le type a eu cent trente-sept fractures ?",
                author: "Nadine", scene: 5, difficulty: 3 },
                { quote: "Aaaaahaha ! Elle est morte la maîtresse !",
                author: "Nadine", scene: 5, difficulty: 1 },
                { quote: "Maintenant, nous allons faire une minute de silence pour tous ces gens qui sont derrière moi.",
                author: "Nadine", scene: 5, difficulty: 3 },
                { quote: "A la boutique cette semaine, le t-shirt de nos plus grands accidentés de la route... Lady Di... Ayrton Senna...",
                author: "Autre", scene: 5, difficulty: 3 },
                { quote: "Eh ben, ça roucoule ici, hein ? C'est un cinéma porno ou quoi ?",
                author: "JC", scene: 6, difficulty: 3 },
                { quote: "D'identité sexuelle... ça veut strictement rien dire, ou alors faut qu'on m'explique.",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "Des gros nénés... un gros ventre... des grosses cuisses... ça change, hein ? Ben oui ! Ça change des magazines...",
                author: "Autre", scene: 6, difficulty: 2 },
                { quote: "Ma main à couper que ça va encore tourner autour du trou de balle, cette histoire...",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "Qu'est-ce qu'il a celui-là, on se connait ?",
                author: "JC", scene: 6, difficulty: 5 },
                { quote: "Comment je sais que c'est toi, ben... je vois ton nom qui clignote sur l'écran, tiens. T'es vraiment con...",
                author: "Greg", scene: 6, difficulty: 3 },
                { quote: "Excuse-moi... oho... excuse-moi... ça te dérangerait pas de sortir pour aller téléphoner ?",
                author: "Stef", scene: 6, difficulty: 4 },
                { quote: "Ta gueule ! Je parle, là.",
                author: "Greg", scene: 6, difficulty: 4 },
                { quote: "Non, c'est pas à toi que je parle. Non, c'est à un crétin, là. Un mongol.",
                author: "Greg", scene: 6, difficulty: 3 },
                { quote: "Tu sors pour téléphoner ou alors t'éteins ton téléphone.",
                author: "Stef", scene: 6, difficulty: 3 },
                { quote: "Eh, achètes des cotons-tige alors, il te demande pour la deuxième et la dernière fois si tu peux pas sortir pour téléphoner à ta pouffiasse !",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "Tu veux te battre, c'est ça ? Vas-y connard !",
                author: "Greg", scene: 6, difficulty: 3 },
                { quote: "Il est tout à fait fou ce type...",
                author: "JC", scene: 6, difficulty: 3 },
                { quote: "Au cinéma tu restes debout, toi ? Assiez-toi ! Et regardes seulement devant toi.",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "Non mais t'as vu ça madame ? T'as vu comment il me parle ?",
                author: "JC", scene: 6, difficulty: 3 },
                { quote: "Non c'est rien, c'est un crétin, là...",
                author: "Greg", scene: 6, difficulty: 5 },
                { quote: "Mais ce type le fait exprès, tsé !",
                author: "JC", scene: 6, difficulty: 4 },
                { quote: "Mais non, c'est pas à toi que je parle, mais tu comprends jamais rien, t'es vraiment conne !",
                author: "Greg", scene: 6, difficulty: 2 },
                { quote: "La première c'est pour te faire la leçon, petit con ! La deuxième c'est pour le principe ! La troisième c'est parce que jamais deux sans trois !",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "Qu'est-ce que vous faites le quinze août ? Non c'est parce que... je fête mes dix-huit ans.",
                author: "Fabienne", scene: 6, difficulty: 2 },
                { quote: "J'organise une petite fête au Zoute. Ça va être bien, j'invite toute la Belgique...",
                author: "Fabienne", scene: 6, difficulty: 3 },
                { quote: "C'est quoi cette tutte ? Elle a aussi été bercée trop près du mur, celle-là ?",
                author: "JC", scene: 6, difficulty: 3 },
                { quote: "Tiens ! De la part du bébé manager. Encore une petite ? Oh elle a dû faire mal, celle-là.",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "Tu vois, moi, ce que j'apprécie, moi, dans ce dancing, c'est ce côté un peu palace, quoi, Pretty Woman...",
                author: "Claudy", scene: 7, difficulty: 2 },
                { quote: "Ohla ! On est mal réveillée ?",
                author: "Claudy", scene: 7, difficulty: 3 },
                { quote: "t'as pas pensé quand t'as laissé rentrer les Albanais là, fais attention avec ça... faut pas laisser rentrer, ça.",
                author: "Claudy", scene: 7, difficulty: 2 },
                { quote: "Ça doit rester chez nous quoi, ici, tu comprends ?",
                author: "Claudy", scene: 7, difficulty: 4 },
                { quote: "Ah, mais voilà le plus beau.",
                author: "Daisy", scene: 7, difficulty: 3 },
                { quote: "Bah, je vais te demander une petite bière, je crève de soif, moi, ici.",
                author: "Claudy", scene: 7, difficulty: 3 },
                { quote: "Eh ben, pas évident.",
                author: "Claudy", scene: 7, difficulty: 4 },
                { quote: "pour le moment, je rame. Je rime et je rame comme tartine et boterham, comme on dit.",
                author: "Claudy", scene: 7, difficulty: 2 },
                { quote: "Non je te jure, par moment, j'en prends plein la gueule. La loi universelle des séries, comme on dit.",
                author: "Claudy", scene: 7, difficulty: 2 },
                { quote: "Ouais, on a de gros problèmes avec la rage, la dioxine, enfin c'est toujours les mêmes trucs qui reviennent",
                author: "Claudy", scene: 7, difficulty: 2 },
                { quote: "Et à propos de vieille truie, toi, comment ça va ?",
                author: "Claudy", scene: 7, difficulty: 2 },
                { quote: "Comme il est méchant toujours avec moi, celui-là !",
                author: "Daisy", scene: 7, difficulty: 3 },
                { quote: "C'est plus une boutade qu'autre chose.",
                author: "Claudy", scene: 7, difficulty: 3 },
                { quote: "si je suis si souvent si bien accompagné, c'est pour mon pognon. C'est pas pour mon odeur. Et ça, ça fait mal.",
                author: "Claudy", scene: 7, difficulty: 2 },
                { quote: "Ouah, c'est Michael Jackson, ah ça j'adore, ça ! T'entends ? Michael Jackson !",
                author: "Claudy", scene: 7, difficulty: 1 },
                { quote: "ben c'est le seul blanc qu'arrive à faire de la musique comme les black, c'est pas compliqué.",
                author: "Claudy", scene: 7, difficulty: 3 },
                { quote: "Pour moi, en deux mots, au-dessus de lui il y a personne, en-dessous de lui il y a personne.",
                author: "Claudy", scene: 7, difficulty: 2 },
                { quote: "Tiens, remet-le moi un peu plus fort, il y a que moi qui danse, ici.",
                author: "Claudy", scene: 7, difficulty: 2 },
                { quote: "Quoi... c'est mon engin que tu regardes, là ? Féroce, ça.",
                author: "Laurence", scene: 8, difficulty: 4 },
                { quote: "Pistolet tchèque semi-automatique, plastique léger, dix-sept coups.",
                author: "Laurence", scene: 8, difficulty: 2 },
                { quote: "Ah, ça, ça t'arrête un bus scolaire en pleine course... peut-être même un avion.",
                author: "Laurence", scene: 8, difficulty: 3 },
                { quote: "J'ai toujours été passionnée par les armes à feu, moi",
                author: "Laurence", scene: 8, difficulty: 3 },
                { quote: "Ils ont failli me poignarder. Ils avaient pas de poignard, mais... ils m'ont tapé dans le dos",
                author: "Greg", scene: 8, difficulty: 2 },
                { quote: "ils m'ont prit mon GSM, un tout nouveau...",
                author: "Greg", scene: 8, difficulty: 3 },
                { quote: "j'ai fait du judo quand j'étais petit donc j'ai pu maîtriser la situation plus ou moins, quoi...",
                author: "Greg", scene: 8, difficulty: 2 },
                { quote: "Mais... il aurait fait ça pourquoi ? Pour le plaisir ?",
                author: "Laurence", scene: 8, difficulty: 3 },
                { quote: "Elle va passer à la casserole, ça c'est moi qui te le dis.",
                author: "Daisy", scene: 9, difficulty: 4 },
                { quote: "Te trompe pas, parce que j'ai mis une dose de cheval...",
                author: "Daisy", scene: 9, difficulty: 2 },
                { quote: "tiens, petite coupette... tchin-tchin... prosit... cheers",
                author: "Claudy", scene: 9, difficulty: 2 },
                { quote: "soi-disant, soi-disant mon téléphone aurait sonné...",
                author: "Greg", scene: 10, difficulty: 3 },
                { quote: "Non mais, attendez, ça on le dit avant le film, de le couper, le portable. On le re-dit après les publicités, d'accord ?",
                author: "Laurence", scene: 10, difficulty: 2 },
                { quote: "On va quand même pas faire rallumer la salle toutes les cinq minutes pour dire qu'il faut couper son GSM ?!",
                author: "Laurence", scene: 10, difficulty: 3 },
                { quote: "Vrai ou faux ? ",
                author: "Laurence", scene: 10, difficulty: 5 },
                { quote: "Oui ou non ? J'ai raison ?",
                author: "Laurence", scene: 10, difficulty: 4 },
                { quote: "En plus ça pue, les gens puent, au cinéma. Les gens puent plus au cinéma, d'ailleurs.",
                author: "Laurence", scene: 10, difficulty: 3 },
                { quote: "Bon je vais quand même appeler mon pote Maurice, là",
                author: "Laurence", scene: 10, difficulty: 4 },
                { quote: "Bon attention, je suis pas mauvaise mais je dessine pas comme Tintin.",
                author: "Laurence", scene: 10, difficulty: 2 },
                { quote: "Ouais ben c'est ce que je dis. Je dessine pas comme Tintin.",
                author: "Laurence", scene: 10, difficulty: 2 },
                { quote: "il sentait l'alcool, je vous assure, mais dans tout le cinéma. Un alcoolique !",
                author: "Greg", scene: 10, difficulty: 2 },
                { quote: "Mais où tu veux que je trouve un coupé Mercedes, moi ? Ouais je sais, c'est ce qui part le mieux en Afrique.",
                author: "JC", scene: 11, difficulty: 2 },
                { quote: "C'est excessivement énervant, tes commandes de dernière minute...",
                author: "JC", scene: 11, difficulty: 3 },
                { quote: "Parce que moi je suis toujours bon pour te rendre service...",
                author: "JC", scene: 11, difficulty: 4 },
                { quote: "Putain, vise-moi ça, dis !",
                author: "JC", scene: 11, difficulty: 5 },
                { quote: "Nom de Dieu, qu'est-ce que c'est ce bordel, là ?",
                author: "Claudy", scene: 11, difficulty: 3 },
                { quote: "Putain j'ai un big problème.",
                author: "Greg", scene: 12, difficulty: 4 },
                { quote: "Ah bon t'es pas mort, c'est le principal.",
                author: "Fabienne", scene: 12, difficulty: 3 },
                { quote: "Je suis dégoûté, on m'a volé mon portable.",
                author: "Greg", scene: 12, difficulty: 2 },
                { quote: "Je sais pas, et ta carte de téléphone ? Faut l'annuler cette carte ?",
                author: "Fabienne", scene: 12, difficulty: 2 },
                { quote: "c'est un truc que j'ai trouvé sur ebazar, pour pas payer.",
                author: "Greg", scene: 12, difficulty: 3 },
                { quote: "Ben écoute, démerdes-toi, prend le bus, pour une fois.",
                author: "Fabienne", scene: 12, difficulty: 2 },
                { quote: "C'est une cabine publique, pour ton information. Pas de GSM ? ",
                author: "Claudy", scene: 12, difficulty: 2 },
                { quote: "On est Place Poelaert, ici grand. On est pas sur la Croisette.",
                author: "Claudy", scene: 12, difficulty: 3 },
                { quote: "je crois que je vais lui faire une manchette japonaise dans sa gueule...",
                author: "Greg", scene: 12, difficulty: 2 },
                { quote: "Ou tu sors, ou je te sors, mais faudra prendre une décision.",
                author: "Claudy", scene: 12, difficulty: 1 },
                { quote: "Et tes lunettes, va, couillon. Tu verras peut-être plus clair la prochaine fois.",
                author: "Claudy", scene: 12, difficulty: 2 },
                { quote: "Dis, je viens de me faire carjacker. Je dis, je viens de me faire carjacker. On a volé l'auto.",
                author: "Claudy", scene: 12, difficulty: 1 },
                { quote: "Non, je n'ai rien su faire, j'ai tâché de courir derrière, qu'est-ce tu veux faire ?",
                author: "Claudy", scene: 12, difficulty: 2 },
                { quote: "Non euh, avec ma veste en cuir dedans avec les septante mille balles dedans.",
                author: "Claudy", scene: 12, difficulty: 2 },
                { quote: "ben non, tes lunettes, qu'est-ce tu veux, M'man, ben non, dans la boite à gants. La boite à gants elle reste dans la voiture.",
                author: "Claudy", scene: 12, difficulty: 1 },
                { quote: "Si tu sais venir... où quand... on était petits on allait jouer au snooker avec Papa. Au café où c'est qu'il y a Duvel en grand, là.",
                author: "Claudy", scene: 12, difficulty: 2 },
                { quote: "Mais tout de suite, fais vite hein parce que... je veux quitter cette ville.",
                author: "Claudy", scene: 12, difficulty: 3 },
                { quote: "Je deviens fou, moi, ici. Quelle violence.",
                author: "Claudy", scene: 12, difficulty: 3 },
                { quote: "Il est vachement bien ton bureau... ",
                author: "JC", scene: 13, difficulty: 4 },
                { quote: "Quelle chaleur, hein ? Je suis toute mouillée, là.",
                author: "Sylvie", scene: 13, difficulty: 2 },
                { quote: "Bon moi j'ai un peu la tête dans le cul mais... ça va aller...",
                author: "Stef", scene: 13, difficulty: 3 },
                { quote: "oh ben il faut un petit peu... lâcher la soupape de temps en temps...",
                author: "Sylvie", scene: 13, difficulty: 3 },
                { quote: "on peut pas toujours vivre comme une casserole sur le feu.",
                author: "Sylvie", scene: 13, difficulty: 2 },
                { quote: "En ce moment ça va pas du tout du tout... une petite crise post-adolescence...",
                author: "Sylvie", scene: 13, difficulty: 4 },
                { quote: "Mais si, une petite mignonne qui court toujours toute nue en train de chercher sa culotte...",
                author: "Sylvie", scene: 13, difficulty: 2 },
                { quote: "Vous voulez rien boire ? On peut peut-être se tutoyer ? Tu veux boire quelque chose ?",
                author: "Sylvie", scene: 13, difficulty: 2 },
                { quote: "Je boirais bien une petite canette... une petite Vedett, c'est bien.",
                author: "Stef", scene: 13, difficulty: 3 },
                { quote: "Ah le soft, c'est pas ton truc, toi.",
                author: "Sylvie", scene: 13, difficulty: 3 },
                { quote: "Mets-toi à ma place, à qui je vais revendre ça, moi ? Un crollé dans ton genre ?",
                author: "JC", scene: 14, difficulty: 2 },
                { quote: "Le serpent revient très fort à la mode, mais pas autant que le cuir.",
                author: "JC", scene: 14, difficulty: 3 },
                { quote: "Dis, t'a fait des mèches ?",
                author: "JC", scene: 14, difficulty: 3 },
                { quote: "Je vais couper, je crois. Mais l'autre il aime bien les cheveux longs...",
                author: "Autre", scene: 14, difficulty: 4 },
                { quote: "Je te laisse, démerdes-toi avec ta peau de vache, là.",
                author: "Autre", scene: 14, difficulty: 4 },
                { quote: "T'as vu ça où que c'était à la mode, ce truc ?",
                author: "Aziz", scene: 14, difficulty: 3 },
                { quote: "Eh, on est pas chez H&M ici",
                author: "Aziz", scene: 14, difficulty: 3 },
                { quote: "Ouais il me semblait bien que j'avais entendu.",
                author: "JC", scene: 14, difficulty: 3 },
                { quote: "Putain vieux, regarde, elle sent la merde ta veste.",
                author: "Aziz", scene: 14, difficulty: 3 },
                { quote: "Mais non. C'est le cuir, ça.",
                author: "JC", scene: 14, difficulty: 2 },
                { quote: "Sur la tête de ma mère elle sent le cochon, regarde mon vieux !",
                author: "Aziz", scene: 14, difficulty: 2 },
                { quote: "Ça t'intéresse pas une PlayStation ?",
                author: "JC", scene: 14, difficulty: 3 },
                { quote: "Dis, t'es au courant qu'il y a une gamine avec des yeux de cocker dans ton coffre, là ?",
                author: "Autre", scene: 14, difficulty: 2 },
                { quote: "Ouais d'accord mais... tu remballes ta roue de secours.",
                author: "Autre", scene: 14, difficulty: 3 },
                { quote: "Oh ! Tu bois pas tout, gros tas !",
                author: "Autre", scene: 15, difficulty: 3 },
                { quote: "Ohlala, regarde la tête qu'il a, dis ! Il ressemble à son père, il est moche, tiens.",
                author: "Autre", scene: 15, difficulty: 2 },
                { quote: "On a bien essayé de le placer, mais on y arrive pas.",
                author: "Autre", scene: 15, difficulty: 4 },
                { quote: "C'est comme aux 3 Suisses, ils le ramènent toujours. Je peux quand même pas le piquer, non ?",
                author: "Autre", scene: 15, difficulty: 2 },
                { quote: "Ah excuses-moi, je ne t'avais pas vu.",
                author: "Claudy", scene: 15, difficulty: 4 },
                { quote: "Tu me remets une bière aussi, s'il te plaît. Je crève de soif, moi, ici. Et une fraîche si tu as !",
                author: "Claudy", scene: 15, difficulty: 2 },
                { quote: "Oui, la même.",
                author: "Claudy", scene: 15, difficulty: 4 },
                { quote: "Et tu vas en profiter pour changer de verre, aussi. Celui-là il goûte le savon.",
                author: "Claudy", scene: 15, difficulty: 2 },
                { quote: "Tu prends les gens pour des cons ?",
                author: "Claudy", scene: 15, difficulty: 4 },
                { quote: "Tu me remettras la petite sœur.",
                author: "Claudy", scene: 15, difficulty: 2 },
                { quote: "Enfin, encore une chance que j'ai pas eu la bouche ouverte...",
                author: "Sylvie", scene: 16, difficulty: 3 },
                { quote: "Ça va ? C'est la pause rigolade ou quoi ?",
                author: "Baudoin", scene: 16, difficulty: 3 },
                { quote: "Ah c'est toi qui a les glaçons. Il n'y a plus un seul glaçon dans ce frigo, qu'est-ce qui s'est passé ici ?",
                author: "Baudoin", scene: 16, difficulty: 2 },
                { quote: "Va un peu jouer avec ta tondeuse, toi, idiot.",
                author: "Baudoin", scene: 16, difficulty: 2 },
                { quote: "Quand c'est pour avoir du pognon pour faire tes courses, c'est bon...",
                author: "Baudoin", scene: 16, difficulty: 2 },
                { quote: "Dis, on t'a jamais appris à manger avec la bouche fermée, toi ?",
                author: "Claudy", scene: 17, difficulty: 3 },
                { quote: "J'ai l'impression d'être à côté d'un camion poubelle qui travaille, moi, ici.",
                author: "Claudy", scene: 17, difficulty: 2 },
                { quote: "Connasse, va.",
                author: "Claudy", scene: 17, difficulty: 5 },
                { quote: "C'est excessivement énervant d'entendre quelqu'un qui mange des chips pour celui qui n'en mange pas !",
                author: "Claudy", scene: 17, difficulty: 1 },
                { quote: "Education minimum.",
                author: "Claudy", scene: 17, difficulty: 2 },
                { quote: "Je vais te taper ça à l'abattoir, ça va être vite fait tsé, moi.",
                author: "Claudy", scene: 17, difficulty: 2 },
                { quote: "Petite bite",
                author: "Sylvie", scene: 18, difficulty: 4 },
                { quote: "Avec son gros jouet... petite bite...",
                author: "Sylvie", scene: 19, difficulty: 2 },
                { quote: "T'embrasses pas ta mère ?",
                author: "Autre", scene: 19, difficulty: 3 },
                { quote: "Je te dis, c'est... une seconde, ça a prit une seconde.",
                author: "Claudy", scene: 19, difficulty: 2 },
                { quote: "Je te dis, je découvre maintenant seulement je commence à réaliser ce qui s'est passé.",
                author: "Claudy", scene: 19, difficulty: 2 },
                { quote: "Je n'ai rien su faire.",
                author: "Claudy", scene: 19, difficulty: 3 },
                { quote: "Je n'ai... j'ai vraiment pros... prosterné ou prostré je ne sais... je ne sais même plus comment on dit.",
                author: "Claudy", scene: 19, difficulty: 2 },
                { quote: "Là, je n'en peux plus, je suis au bout du rouleau.",
                author: "Claudy", scene: 19, difficulty: 3 },
                { quote: "J'ai envie de rentrer, me foutre mes savates et terminé bonsoir, quoi.",
                author: "Claudy", scene: 19, difficulty: 2 },
                { quote: "Arrête de me regarder en essayant que j'explique l'histoire. Je ne sais pas l'expliquer...",
                author: "Claudy", scene: 19, difficulty: 2 }
              ].freeze
    end
  end
end
