module Games
  module Dikkeneks
    class Data
      include ActiveModel::Model

      CHARACTERS = [ "JC", "Stef", "Greg", "Nadine", "Claudy", "Natasha", "Sylvie", "Daisy",
                    "Laurence", "Aziz", "Fabienne", "Autre" ].freeze

      QUOTES = [
                { quote: "Qu'est-ce qui ne va pas encore ? Le grand amour, c'est ça ? Et tu veux pas commencer avec un petit amour... tout de suite le grand !",
                author: "JC", scene: 1, difficulty: 2 },
                { quote: "Avant la fin de la semaine, je te trouve une gonzesse. T'auras plus qu'à te pencher... ça tu sais faire tout seul.",
                author: "JC", scene: 2, difficulty: 2 },
                { quote: "On est tombé sur une cinglée... un cas clinique désespéré.",
                author: "JC", scene: 3, difficulty: 3 },
                { quote: "On va peut-être pas mettre la barre trop haut, d'accord ?",
                author: "JC", scene: 4, difficulty: 3 },
                { quote: "Quoique se taper une moche, c'est pas ce qu'il y a de plus simple. Elles sont terriblement méfiantes, les laides, tu vois ? Les laides.",
                author: "JC", scene: 5, difficulty: 2 },
                { quote: "On va attaquer la middle-class. Avant la fin de la semaine, tu rencontres la femme de ta vie !",
                author: "JC", scene: 6, difficulty: 2 },
                { quote: "Ouais dis, Monique, c'est moi. Dis, tu vas me rendre un service. Annule-moi un peu ce rendez-vous avec ces deux imbéciles de l'école de TV, là.",
                author: "Claudy", scene: 7, difficulty: 2 },
                { quote: "J'ai pas le temps de faire ça... j'ai matériellement pas le temps de faire ça.",
                author: "Claudy", scene: 8, difficulty: 3 },
                { quote: "Des trous de culs pareils, ça m'intéresse pas.",
                author: "Claudy", scene: 9, difficulty: 4 },
                { quote: "I.A.D. ? Connais pas, inconnu au bataillon, jamais entendu.",
                author: "Claudy", scene: 10, difficulty: 2 },
                { quote: "Bon, c'est pour le fameux travail de fin d'études, là ?",
                author: "Claudy", scene: 11, difficulty: 3 },
                { quote: "Ça doit durer combien de temps ? sept-huit minutes ?",
                author: "Claudy", scene: 12, difficulty: 5 },
                { quote: "Bon on va y aller, hein. Je suis prêt. Vous dites pas 'Action!' ? Dites, fieux, eh ! oh !",
                author: "Claudy", scene: 13, difficulty: 3 },
                { quote: "Je dis ça parce que je regardais ton objectif. C'est du digital, hein ? Du trente-cinq millimètres ?",
                author: "Claudy", scene: 14, difficulty: 2 },
                { quote: "En fait, je suis photographe de... je fais des photos de charme, en somme. Mais c'est un peu hors-contexte.",
                author: "Claudy", scene: 15, difficulty: 2 },
                { quote: "Je suis Directeur and Sales Marketing-Manager des Abattoirs d'Anderlecht.",
                author: "Claudy", scene: 16, difficulty: 1 },
                { quote: "Quand les bêtes arrivent, elles sont cent-cinquante dans un camion. Pourquoi cent-cinquante ? De façon à ne pas trébucher pendant le transport.",
                author: "Claudy", scene: 17, difficulty: 2 },
                { quote: "Une fois qu'elles arrivent ici, c'est pas compliqué, elles suivent la ligne blanche, et on les dirige inéluctablement, elles sont deux par deux, vers la zone d'abattage. c'est peut-être la partie la moins marrante, quoique.",
                author: "Claudy", scene: 18, difficulty: 3 },
                { quote: "On a jamais dû tirer deux fois, si vous voulez... si vous voyez ce que je veux dire.",
                author: "Claudy", scene: 19, difficulty: 2 },
                { quote: "Enfin moi c'est mon petit pêché mignon.",
                author: "Claudy", scene: 20, difficulty: 5 },
                { quote: "Une fois que la bête est décédée, elle se dirige... enfin on la dirige, étant donné qu'elle ne marche plus...",
                author: "Claudy", scene: 21, difficulty: 2 },
                { quote: "Ecoute fieu, tu commences par me faire chier avec ta torche, hein ? Ça fait depuis le début que tu m'emmerdes. Tu m'as déjà fourré la gueule là-bas. Ça va suffir maintenant ?",
                author: "Claudy", scene: 22, difficulty: 2 },
                { quote: "J'ai l'impression qu'on m'a donné les deux clowns de l'I.A.D. là, le fond du panier.",
                author: "Claudy", scene: 23, difficulty: 1 },
                { quote: "J'allais y venir. Chaque chose arrive en son temps. Tu vas pas me dire toi ce que je dois raconter.",
                author: "Claudy", scene: 24, difficulty: 3 },
                { quote: "Faut savoir que sur une bête de sept-cents kilos, il y a trois-cent-cinquante kilos qui sont considérés comme matières ou restes impropres à la consommation.",
                author: "Claudy", scene: 25, difficulty: 2 },
                { quote: "Je veux dire par la que vous verrez jamais dans une boucherie des narines, un scrotum, un anus ou euh... des intestins par exemple.",
                author: "Claudy", scene: 26, difficulty: 2 },
                { quote: "Les intestins, ce n'est jamais que de l'herbe digérée. On appelle ça plus communément de la merde, pour votre information.",
                author: "Claudy", scene: 27, difficulty: 2 },
                { quote: "On racle tout ça, on tape tout dans des grandes bassines... nous autres on appelle ça des piscines.",
                author: "Claudy", scene: 28, difficulty: 3 },
                { quote: "Enfin, ça c'est notre petite popote, c'est le pot belge comme on dit.",
                author: "Claudy", scene: 29, difficulty: 4 },
                { quote: "C'est compris ? Un beau matin, vous allez aussi vous retrouver dans une cuve.",
                author: "Claudy", scene: 30, difficulty: 5 },
                { quote: "Tchao Polak ! Fais-moi un grand paquet de frites avec sauce, s'il te plait.",
                author: "Aziz", scene: 31, difficulty: 3 },
                { quote: "Euh... je sais pas moi... sauce Dallas. Mets-moi la sauce à part. Et trois boulettes avec.",
                author: "Aziz", scene: 32, difficulty: 2 },
                { quote: "Omar ! La sauce à part ou sur les frites ?",
                author: "Aziz", scene: 33, difficulty: 3 },
                { quote: "Sur les boulettes ! Et tu mets six, sept fricadelles aussi.",
                author: "Autre", scene: 34, difficulty: 4 },
                { quote: "Dix bières s'il vous plait ? Dix Vedett.",
                author: "Stef", scene: 35, difficulty: 4 },
                { quote: "Comment il est à l'aise, lui. T'es aveugle ou quoi ? J'étais juste en train de commander des Bicky. Tu joues avec ta vie, toi.",
                author: "Aziz", scene: 36, difficulty: 2 },
                { quote: "Qu'est-ce qu'il a ce fils de pute ? Allez viens !",
                author: "Aziz", scene: 37, difficulty: 5 },
                { quote: "Le type y vient à l'aise, s'excuse même pas, il me dépasse... t'es poli ou t'es pas poli, toi ?",
                author: "Aziz", scene: 38, difficulty: 1 },
                { quote: "T'es pas en classe verte, toi ? Il me semblait bien que c'était toi ! Avec ton vieil accent de chanteur de rap, là... Hip-hop.",
                author: "JC", scene: 39, difficulty: 2 },
                { quote: "Et cette manie que tu as de cracher partout comme un lama. C'est excessivement énervant.",
                author: "JC", scene: 40, difficulty: 2 },
                { quote: "C'est mon pote. Et tu lui parles autrement ! Excuses-toi. Excuses-toi tout de suite !",
                author: "JC", scene: 41, difficulty: 3 },
                { quote: "Tu sais ce qu'il y a dans une fricadelle ? Hein ? J'ai vu un reportage là-dessus.",
                author: "JC", scene: 42, difficulty: 4 },
                { quote: "Ah, ça du porc, c'est sûr il y en a pas, hein. Mais tu donnes ça à un chien, il le bouffe pas non plus.",
                author: "JC", scene: 43, difficulty: 3 },
                { quote: "Dis, je peux te poser une question ? Le prend pas mal, mais qu'est-ce que tu comptes faire, toi, pour la rentrée ?",
                author: "Sylvie", scene: 44, difficulty: 2 },
                { quote: "Tu peux pas continuer comme ça à échouer tous les ans. C'est échec sur échec.",
                author: "Sylvie", scene: 45, difficulty: 5 },
                { quote: "Alors ça, guindailler, la grasse matinée, ça, ça va, ça. Ça tu sais faire.",
                author: "Sylvie", scene: 46, difficulty: 4 },
                { quote: "Si moi aujourd'hui, je suis au chômage, c'est quand même pas de ma faute. Moi j'avais rien demandé, à dix-sept ans... rien.",
                author: "Sylvie", scene: 47, difficulty: 3 },
                { quote: "Moi je voulais faire le barreau, moi. Pas faire des moutards avec l'autre con, là.",
                author: "Sylvie", scene: 48, difficulty: 2 },
                { quote: "Moi, je voulais devenir... une grande psychologue, tu vois ? Aider les gens, rendre service, M.S.F., tout le bordel.",
                author: "Sylvie", scene: 49, difficulty: 3 },
                { quote: "Et quand tes parents sont morts, ma vie aussi elle a changé.",
                author: "Sylvie", scene: 50, difficulty: 4 },
                { quote: "Eh, bah eh, le jour de l'enterrement, il a fallu que je devienne maman, moi... d'un coup. Bonjour !",
                author: "Sylvie", scene: 51, difficulty: 2 },
                { quote: "Finalement c'est un peu ça le but dans la vie, non ? Réussir à rien foutre.",
                author: "Natasha", scene: 52, difficulty: 2 },
                { quote: "Dis-donc toi, goulaf ! Tu sais pas lire ? C'est interdit de manger dans les musées !",
                author: "Nadine", scene: 53, difficulty: 3 },
                { quote: "Comme quoi, on ne le dira jamais assez : la ceinture ! Un petit clic vaut mieux qu'une grande claque !",
                author: "Nadine", scene: 54, difficulty: 2 },
                { quote: "Alors les enfants ? Qui veut jouer au mort ? Qui a déjà eu un accident de voiture ici ? Toi ? Toi ? Toi ? Personne ? Eh ben ça va venir, alors.",
                author: "Nadine", scene: 55, difficulty: 2 },
                { quote: "A 18 ans on commence à boire... et puis on veut impressionner ses amis. Et paf ! C'est le platane assuré en revenant de Louvain-la-Neuve.",
                author: "Nadine", scene: 56, difficulty: 3 },
                { quote: "Toi Charlotte, tu sais ce que c'est qu'un pare-brise, hein ? Eh oui !",
                author: "Nadine", scene: 57, difficulty: 3 },
                { quote: "Si aujourd'hui tu ressembles plus à Albator qu'à Candy, c'est parce que ta maman, elle flûte !",
                author: "Nadine", scene: 58, difficulty: 2 },
                { quote: "Elle est jolie cette grille, non ? Vous savez que le type a eu cent trente-sept fractures ?",
                author: "Nadine", scene: 59, difficulty: 3 },
                { quote: "Aaaaahaha ! Elle est morte la maîtresse !",
                author: "Nadine", scene: 60, difficulty: 1 },
                { quote: "Maintenant, nous allons faire une minute de silence pour tous ces gens qui sont derrière moi.",
                author: "Nadine", scene: 61, difficulty: 3 },
                { quote: "A la boutique cette semaine, le t-shirt de nos plus grands accidentés de la route... Lady Di... Ayrton Senna...",
                author: "Autre", scene: 62, difficulty: 3 },
                { quote: "Eh ben, ça roucoule ici, hein ? C'est un cinéma porno ou quoi ?",
                author: "JC", scene: 63, difficulty: 3 },
                { quote: "D'identité sexuelle... ça veut strictement rien dire, ou alors faut qu'on m'explique.",
                author: "JC", scene: 64, difficulty: 2 },
                { quote: "Des gros nénés... un gros ventre... des grosses cuisses... ça change, hein ? Ben oui ! Ça change des magazines...",
                author: "Autre", scene: 65, difficulty: 2 },
                { quote: "Ma main à couper que ça va encore tourner autour du trou de balle, cette histoire...",
                author: "JC", scene: 66, difficulty: 2 },
                { quote: "Qu'est-ce qu'il a celui-là, on se connait ?",
                author: "JC", scene: 67, difficulty: 5 },
                { quote: "Comment je sais que c'est toi, ben... je vois ton nom qui clignote sur l'écran, tiens. T'es vraiment con...",
                author: "Greg", scene: 68, difficulty: 3 },
                { quote: "Excuse-moi... oho... excuse-moi... ça te dérangerait pas de sortir pour aller téléphoner ?",
                author: "Stef", scene: 69, difficulty: 4 },
                { quote: "Ta gueule ! Je parle, là.",
                author: "Greg", scene: 70, difficulty: 4 },
                { quote: "Non, c'est pas à toi que je parle. Non, c'est à un crétin, là. Un mongol.",
                author: "Greg", scene: 71, difficulty: 3 },
                { quote: "Tu sors pour téléphoner ou alors t'éteins ton téléphone.",
                author: "Stef", scene: 72, difficulty: 3 },
                { quote: "Eh, achètes des cotons-tige alors, il te demande pour la deuxième et la dernière fois si tu peux pas sortir pour téléphoner à ta pouffiasse !",
                author: "JC", scene: 73, difficulty: 2 },
                { quote: "Tu veux te battre, c'est ça ? Vas-y connard !",
                author: "Greg", scene: 74, difficulty: 3 },
                { quote: "Il est tout à fait fou ce type...",
                author: "JC", scene: 75, difficulty: 3 },
                { quote: "Au cinéma tu restes debout, toi ? Assiez-toi ! Et regardes seulement devant toi.",
                author: "JC", scene: 76, difficulty: 2 },
                { quote: "Non mais t'as vu ça madame ? T'as vu comment il me parle ?",
                author: "JC", scene: 77, difficulty: 3 },
                { quote: "Non c'est rien, c'est un crétin, là...",
                author: "Greg", scene: 78, difficulty: 5 },
                { quote: "Mais ce type le fait exprès, tsé !",
                author: "JC", scene: 79, difficulty: 4 },
                { quote: "Mais non, c'est pas à toi que je parle, mais tu comprends jamais rien, t'es vraiment conne !",
                author: "Greg", scene: 80, difficulty: 2 },
                { quote: "La première c'est pour te faire la leçon, petit con ! La deuxième c'est pour le principe ! La troisième c'est parce que jamais deux sans trois !",
                author: "JC", scene: 81, difficulty: 2 },
                { quote: "Qu'est-ce que vous faites le quinze août ? Non c'est parce que... je fête mes dix-huit ans.",
                author: "Fabienne", scene: 82, difficulty: 2 },
                { quote: "J'organise une petite fête au Zoute. Ça va être bien, j'invite toute la Belgique...",
                author: "Fabienne", scene: 83, difficulty: 3 },
                { quote: "C'est quoi cette tutte ? Elle a aussi été bercée trop près du mur, celle-là ?",
                author: "JC", scene: 84, difficulty: 3 },
                { quote: "Tiens ! De la part du bébé manager. Encore une petite ? Oh elle a dû faire mal, celle-là.",
                author: "JC", scene: 85, difficulty: 2 },
                { quote: "Tu vois, moi, ce que j'apprécie, moi, dans ce dancing, c'est ce côté un peu palace, quoi, Pretty Woman...",
                author: "Claudy", scene: 86, difficulty: 2 },
                { quote: "Ohla ! On est mal réveillée ?",
                author: "Claudy", scene: 87, difficulty: 3 },
                { quote: "T'as pas pensé quand t'as laissé rentrer les Albanais là, fais attention avec ça... faut pas laisser rentrer, ça.",
                author: "Claudy", scene: 88, difficulty: 2 },
                { quote: "Ça doit rester chez nous quoi, ici, tu comprends ?",
                author: "Claudy", scene: 89, difficulty: 4 },
                { quote: "Ah, mais voilà le plus beau.",
                author: "Daisy", scene: 90, difficulty: 3 },
                { quote: "Bah, je vais te demander une petite bière, je crève de soif, moi, ici.",
                author: "Claudy", scene: 91, difficulty: 3 },
                { quote: "Eh ben, pas évident.",
                author: "Claudy", scene: 92, difficulty: 4 },
                { quote: "Pour le moment, je rame. Je rime et je rame comme tartine et boterham, comme on dit.",
                author: "Claudy", scene: 93, difficulty: 2 },
                { quote: "Non je te jure, par moment, j'en prends plein la gueule. La loi universelle des séries, comme on dit.",
                author: "Claudy", scene: 94, difficulty: 2 },
                { quote: "Ouais, on a de gros problèmes avec la rage, la dioxine, enfin c'est toujours les mêmes trucs qui reviennent",
                author: "Claudy", scene: 95, difficulty: 2 },
                { quote: "Et à propos de vieille truie, toi, comment ça va ?",
                author: "Claudy", scene: 96, difficulty: 2 },
                { quote: "Comme il est méchant toujours avec moi, celui-là !",
                author: "Daisy", scene: 97, difficulty: 3 },
                { quote: "C'est plus une boutade qu'autre chose.",
                author: "Claudy", scene: 98, difficulty: 3 },
                { quote: "Si je suis si souvent si bien accompagné, c'est pour mon pognon. C'est pas pour mon odeur. Et ça, ça fait mal.",
                author: "Claudy", scene: 99, difficulty: 2 },
                { quote: "Ouah, c'est Michael Jackson, ah ça j'adore, ça ! T'entends ? Michael Jackson !",
                author: "Claudy", scene: 100, difficulty: 1 },
                { quote: "Ben c'est le seul blanc qu'arrive à faire de la musique comme les black, c'est pas compliqué.",
                author: "Claudy", scene: 101, difficulty: 3 },
                { quote: "Pour moi, en deux mots, au-dessus de lui il y a personne, en-dessous de lui il y a personne.",
                author: "Claudy", scene: 102, difficulty: 2 },
                { quote: "Tiens, remet-le moi un peu plus fort, il y a que moi qui danse, ici.",
                author: "Claudy", scene: 103, difficulty: 2 },
                { quote: "Quoi... c'est mon engin que tu regardes, là ? Féroce, ça.",
                author: "Laurence", scene: 104, difficulty: 4 },
                { quote: "Pistolet tchèque semi-automatique, plastique léger, dix-sept coups.",
                author: "Laurence", scene: 105, difficulty: 2 },
                { quote: "Ah, ça, ça t'arrête un bus scolaire en pleine course... peut-être même un avion.",
                author: "Laurence", scene: 106, difficulty: 3 },
                { quote: "J'ai toujours été passionnée par les armes à feu, moi",
                author: "Laurence", scene: 107, difficulty: 3 },
                { quote: "Ils ont failli me poignarder. Ils avaient pas de poignard, mais... ils m'ont tapé dans le dos",
                author: "Greg", scene: 108, difficulty: 2 },
                { quote: "Ils m'ont prit mon GSM, un tout nouveau...",
                author: "Greg", scene: 109, difficulty: 3 },
                { quote: "J'ai fait du judo quand j'étais petit donc j'ai pu maîtriser la situation plus ou moins, quoi...",
                author: "Greg", scene: 110, difficulty: 2 },
                { quote: "Mais... il aurait fait ça pourquoi ? Pour le plaisir ?",
                author: "Laurence", scene: 111, difficulty: 3 },
                { quote: "Elle va passer à la casserole, ça c'est moi qui te le dis.",
                author: "Daisy", scene: 112, difficulty: 4 },
                { quote: "Te trompe pas, parce que j'ai mis une dose de cheval...",
                author: "Daisy", scene: 113, difficulty: 2 },
                { quote: "Tiens, petite coupette... tchin-tchin... prosit... cheers",
                author: "Claudy", scene: 114, difficulty: 2 },
                { quote: "Soi-disant, soi-disant mon téléphone aurait sonné...",
                author: "Greg", scene: 115, difficulty: 3 },
                { quote: "Non mais, attendez, ça on le dit avant le film, de le couper, le portable. On le re-dit après les publicités, d'accord ?",
                author: "Laurence", scene: 116, difficulty: 2 },
                { quote: "On va quand même pas faire rallumer la salle toutes les cinq minutes pour dire qu'il faut couper son GSM ?!",
                author: "Laurence", scene: 117, difficulty: 3 },
                { quote: "Vrai ou faux ? ",
                author: "Laurence", scene: 118, difficulty: 5 },
                { quote: "Oui ou non ? J'ai raison ?",
                author: "Laurence", scene: 119, difficulty: 4 },
                { quote: "En plus ça pue, les gens puent, au cinéma. Les gens puent plus au cinéma, d'ailleurs.",
                author: "Laurence", scene: 120, difficulty: 3 },
                { quote: "Bon je vais quand même appeler mon pote Maurice, là",
                author: "Laurence", scene: 121, difficulty: 4 },
                { quote: "Bon attention, je suis pas mauvaise mais je dessine pas comme Tintin.",
                author: "Laurence", scene: 122, difficulty: 2 },
                { quote: "Ouais ben c'est ce que je dis. Je dessine pas comme Tintin.",
                author: "Laurence", scene: 123, difficulty: 2 },
                { quote: "Il sentait l'alcool, je vous assure, mais dans tout le cinéma. Un alcoolique !",
                author: "Greg", scene: 124, difficulty: 2 },
                { quote: "Mais où tu veux que je trouve un coupé Mercedes, moi ? Ouais je sais, c'est ce qui part le mieux en Afrique.",
                author: "JC", scene: 125, difficulty: 2 },
                { quote: "C'est excessivement énervant, tes commandes de dernière minute...",
                author: "JC", scene: 126, difficulty: 3 },
                { quote: "Parce que moi je suis toujours bon pour te rendre service...",
                author: "JC", scene: 127, difficulty: 4 },
                { quote: "Putain, vise-moi ça, dis !",
                author: "JC", scene: 128, difficulty: 5 },
                { quote: "Nom de Dieu, qu'est-ce que c'est ce bordel, là ?",
                author: "Claudy", scene: 129, difficulty: 3 },
                { quote: "Putain j'ai un big problème.",
                author: "Greg", scene: 130, difficulty: 4 },
                { quote: "Ah bon t'es pas mort, c'est le principal.",
                author: "Fabienne", scene: 131, difficulty: 3 },
                { quote: "Je suis dégoûté, on m'a volé mon portable.",
                author: "Greg", scene: 132, difficulty: 2 },
                { quote: "Je sais pas, et ta carte de téléphone ? Faut l'annuler cette carte ?",
                author: "Fabienne", scene: 133, difficulty: 2 },
                { quote: "C'est un truc que j'ai trouvé sur ebazar, pour pas payer.",
                author: "Greg", scene: 134, difficulty: 3 },
                { quote: "Ben écoute, démerdes-toi, prend le bus, pour une fois.",
                author: "Fabienne", scene: 135, difficulty: 2 },
                { quote: "C'est une cabine publique, pour ton information. Pas de GSM ? ",
                author: "Claudy", scene: 136, difficulty: 2 },
                { quote: "On est Place Poelaert, ici grand. On est pas sur la Croisette.",
                author: "Claudy", scene: 137, difficulty: 3 },
                { quote: "Je crois que je vais lui faire une manchette japonaise dans sa gueule...",
                author: "Greg", scene: 138, difficulty: 2 },
                { quote: "Ou tu sors, ou je te sors, mais faudra prendre une décision.",
                author: "Claudy", scene: 139, difficulty: 1 },
                { quote: "Et tes lunettes, va, couillon. Tu verras peut-être plus clair la prochaine fois.",
                author: "Claudy", scene: 140, difficulty: 2 },
                { quote: "Dis, je viens de me faire carjacker. Je dis, je viens de me faire carjacker. On a volé l'auto.",
                author: "Claudy", scene: 141, difficulty: 1 },
                { quote: "Non, je n'ai rien su faire, j'ai tâché de courir derrière, qu'est-ce tu veux faire ?",
                author: "Claudy", scene: 142, difficulty: 2 },
                { quote: "Non euh, avec ma veste en cuir dedans avec les septante mille balles dedans.",
                author: "Claudy", scene: 143, difficulty: 2 },
                { quote: "Ben non, tes lunettes, qu'est-ce tu veux, M'man, ben non, dans la boite à gants. La boite à gants elle reste dans la voiture.",
                author: "Claudy", scene: 144, difficulty: 1 },
                { quote: "Si tu sais venir... où quand... on était petits on allait jouer au snooker avec Papa. Au café où c'est qu'il y a Duvel en grand, là.",
                author: "Claudy", scene: 145, difficulty: 2 },
                { quote: "Mais tout de suite, fais vite hein parce que... je veux quitter cette ville.",
                author: "Claudy", scene: 146, difficulty: 3 },
                { quote: "Je deviens fou, moi, ici. Quelle violence.",
                author: "Claudy", scene: 147, difficulty: 3 },
                { quote: "Il est vachement bien ton bureau... ",
                author: "JC", scene: 148, difficulty: 4 },
                { quote: "Quelle chaleur, hein ? Je suis toute mouillée, là.",
                author: "Sylvie", scene: 149, difficulty: 2 },
                { quote: "Bon moi j'ai un peu la tête dans le cul mais... ça va aller...",
                author: "Stef", scene: 150, difficulty: 3 },
                { quote: "Oh ben il faut un petit peu... lâcher la soupape de temps en temps...",
                author: "Sylvie", scene: 151, difficulty: 3 },
                { quote: "On peut pas toujours vivre comme une casserole sur le feu.",
                author: "Sylvie", scene: 152, difficulty: 2 },
                { quote: "En ce moment ça va pas du tout du tout... une petite crise post-adolescence...",
                author: "Sylvie", scene: 153, difficulty: 4 },
                { quote: "Mais si, une petite mignonne qui court toujours toute nue en train de chercher sa culotte...",
                author: "Sylvie", scene: 154, difficulty: 2 },
                { quote: "Vous voulez rien boire ? On peut peut-être se tutoyer ? Tu veux boire quelque chose ?",
                author: "Sylvie", scene: 155, difficulty: 2 },
                { quote: "Je boirais bien une petite canette... une petite Vedett, c'est bien.",
                author: "Stef", scene: 156, difficulty: 3 },
                { quote: "Ah le soft, c'est pas ton truc, toi.",
                author: "Sylvie", scene: 157, difficulty: 3 },
                { quote: "Mets-toi à ma place, à qui je vais revendre ça, moi ? Un crollé dans ton genre ?",
                author: "JC", scene: 158, difficulty: 2 },
                { quote: "Le serpent revient très fort à la mode, mais pas autant que le cuir.",
                author: "JC", scene: 159, difficulty: 3 },
                { quote: "Dis, t'a fait des mèches ?",
                author: "JC", scene: 160, difficulty: 3 },
                { quote: "Je vais couper, je crois. Mais l'autre il aime bien les cheveux longs...",
                author: "Autre", scene: 161, difficulty: 4 },
                { quote: "Je te laisse, démerdes-toi avec ta peau de vache, là.",
                author: "Autre", scene: 162, difficulty: 4 },
                { quote: "T'as vu ça où que c'était à la mode, ce truc ?",
                author: "Aziz", scene: 163, difficulty: 3 },
                { quote: "Eh, on est pas chez H&M ici",
                author: "Aziz", scene: 164, difficulty: 3 },
                { quote: "Ouais il me semblait bien que j'avais entendu.",
                author: "JC", scene: 165, difficulty: 3 },
                { quote: "Putain vieux, regarde, elle sent la merde ta veste.",
                author: "Aziz", scene: 166, difficulty: 3 },
                { quote: "Mais non. C'est le cuir, ça.",
                author: "JC", scene: 167, difficulty: 2 },
                { quote: "Sur la tête de ma mère elle sent le cochon, regarde mon vieux !",
                author: "Aziz", scene: 168, difficulty: 2 },
                { quote: "Ça t'intéresse pas une PlayStation ?",
                author: "JC", scene: 169, difficulty: 3 },
                { quote: "Dis, t'es au courant qu'il y a une gamine avec des yeux de cocker dans ton coffre, là ?",
                author: "Autre", scene: 170, difficulty: 2 },
                { quote: "Ouais d'accord mais... tu remballes ta roue de secours.",
                author: "Autre", scene: 171, difficulty: 3 },
                { quote: "Oh ! Tu bois pas tout, gros tas !",
                author: "Autre", scene: 172, difficulty: 3 },
                { quote: "Ohlala, regarde la tête qu'il a, dis ! Il ressemble à son père, il est moche, tiens.",
                author: "Autre", scene: 173, difficulty: 2 },
                { quote: "On a bien essayé de le placer, mais on y arrive pas.",
                author: "Autre", scene: 174, difficulty: 4 },
                { quote: "C'est comme aux 3 Suisses, ils le ramènent toujours. Je peux quand même pas le piquer, non ?",
                author: "Autre", scene: 175, difficulty: 2 },
                { quote: "Ah excuses-moi, je ne t'avais pas vu.",
                author: "Claudy", scene: 176, difficulty: 4 },
                { quote: "Tu me remets une bière aussi, s'il te plaît. Je crève de soif, moi, ici. Et une fraîche si tu as !",
                author: "Claudy", scene: 177, difficulty: 2 },
                { quote: "Oui, la même.",
                author: "Claudy", scene: 178, difficulty: 4 },
                { quote: "Et tu vas en profiter pour changer de verre, aussi. Celui-là il goûte le savon.",
                author: "Claudy", scene: 179, difficulty: 2 },
                { quote: "Tu prends les gens pour des cons ?",
                author: "Claudy", scene: 180, difficulty: 4 },
                { quote: "Tu me remettras la petite sœur.",
                author: "Claudy", scene: 181, difficulty: 2 },
                { quote: "Enfin, encore une chance que j'ai pas eu la bouche ouverte...",
                author: "Sylvie", scene: 182, difficulty: 3 },
                { quote: "Ça va ? C'est la pause rigolade ou quoi ?",
                author: "Autre", scene: 183, difficulty: 3 },
                { quote: "Ah c'est toi qui a les glaçons. Il n'y a plus un seul glaçon dans ce frigo, qu'est-ce qui s'est passé ici ?",
                author: "Autre", scene: 184, difficulty: 2 },
                { quote: "Va un peu jouer avec ta tondeuse, toi, idiot.",
                author: "Autre", scene: 185, difficulty: 2 },
                { quote: "Quand c'est pour avoir du pognon pour faire tes courses, c'est bon...",
                author: "Autre", scene: 186, difficulty: 2 },
                { quote: "Dis, on t'a jamais appris à manger avec la bouche fermée, toi ?",
                author: "Claudy", scene: 187, difficulty: 3 },
                { quote: "J'ai l'impression d'être à côté d'un camion poubelle qui travaille, moi, ici.",
                author: "Claudy", scene: 188, difficulty: 2 },
                { quote: "Connasse, va.",
                author: "Claudy", scene: 189, difficulty: 5 },
                { quote: "C'est excessivement énervant d'entendre quelqu'un qui mange des chips pour celui qui n'en mange pas !",
                author: "Claudy", scene: 190, difficulty: 1 },
                { quote: "Education minimum.",
                author: "Claudy", scene: 191, difficulty: 2 },
                { quote: "Je vais te taper ça à l'abattoir, ça va être vite fait tsé, moi.",
                author: "Claudy", scene: 192, difficulty: 2 },
                { quote: "Petite bite",
                author: "Sylvie", scene: 193, difficulty: 4 },
                { quote: "Avec son gros jouet... petite bite...",
                author: "Sylvie", scene: 194, difficulty: 2 },
                { quote: "T'embrasses pas ta mère ?",
                author: "Autre", scene: 195, difficulty: 3 },
                { quote: "Je te dis, c'est... une seconde, ça a prit une seconde.",
                author: "Claudy", scene: 196, difficulty: 2 },
                { quote: "Je te dis, je découvre maintenant seulement je commence à réaliser ce qui s'est passé.",
                author: "Claudy", scene: 197, difficulty: 2 },
                { quote: "Je n'ai rien su faire.",
                author: "Claudy", scene: 198, difficulty: 3 },
                { quote: "Je n'ai... j'ai vraiment pros... prosterné ou prostré je ne sais... je ne sais même plus comment on dit.",
                author: "Claudy", scene: 199, difficulty: 2 },
                { quote: "Là, je n'en peux plus, je suis au bout du rouleau.",
                author: "Claudy", scene: 200, difficulty: 3 },
                { quote: "J'ai envie de rentrer, me foutre mes savates et terminé bonsoir, quoi.",
                author: "Claudy", scene: 201, difficulty: 2 },
                { quote: "Arrête de me regarder en essayant que j'explique l'histoire. Je ne sais pas l'expliquer...",
                author: "Claudy", scene: 202, difficulty: 2 },
                { quote: "Ça c'est le mal du siècle, l'alcoolisme.",
                author: "Sylvie", scene: 203, difficulty: 3 },
                { quote: "Et le pire, c'est que lui il était jamais saoul... jamais.",
                author: "Sylvie", scene: 204, difficulty: 3 },
                { quote: "Moi, deux verres... je commence à embrasser tout le monde.",
                author: "Sylvie", scene: 205, difficulty: 3 },
                { quote: "J'ai appris c'est... c'est plus vraiment ta femme.",
                author: "Sylvie", scene: 206, difficulty: 3 },
                { quote: "Elle reviendra... quand elle aura besoin de fric.",
                author: "Autre", scene: 207, difficulty: 2 },
                { quote: "Elle sait très bien de quel côté la tartine est beurrée.",
                author: "Autre", scene: 208, difficulty: 4 },
                { quote: "Il a fait un écart avec une petite asiat' et puis bon... c'est du passé.",
                author: "Sylvie", scene: 209, difficulty: 3 },
                { quote: "Je mettrai des capotes.",
                author: "Autre", scene: 210, difficulty: 4 },
                { quote: "Le cinéma c'est pour voir du monde, parce que... j'ai un home cinema, moi.",
                author: "Autre", scene: 211, difficulty: 2 },
                { quote: "Plus de trois cents DVD... bientôt huit cents grâce à internet.",
                author: "Autre", scene: 212, difficulty: 2 },
                { quote: "On se demande comment ils arrivent à filmer des trucs pareils...",
                author: "Sylvie", scene: 213, difficulty: 4 },
                { quote: "Fais quand même un petit peu attention avec l'alcool...",
                author: "Sylvie", scene: 214, difficulty: 2 },
                { quote: "Qu'est-ce que tu siffles, toi !",
                author: "Sylvie", scene: 215, difficulty: 2 },
                { quote: "Donc je suis allé le voir et je lui ai demandé si c'était du nu.",
                author: "Natasha", scene: 216, difficulty: 2 },
                { quote: "Mais non, c'est pas du nu, c'est de l'art...",
                author: "Claudy", scene: 217, difficulty: 2 },
                { quote: "Il avait l'air gentil, mais bon, fallait aller chez lui.",
                author: "Natasha", scene: 218, difficulty: 2 },
                { quote: "Je vais te demander d'enfiler ça s'il te plait...",
                author: "Claudy", scene: 219, difficulty: 2 },
                { quote: "Non, je suis en shooting, là... je suis en shooting avec mon modèle.",
                author: "Claudy", scene: 220, difficulty: 2 },
                { quote: "Ah, la petite pute...",
                author: "Autre", scene: 221, difficulty: 4 },
                { quote: "Mais... ne la juge pas. Tu ne la connais pas, t'es déjà occupée à la juger.",
                author: "Claudy", scene: 222, difficulty: 2 },
                { quote: "C'est pas un peu vulgaire, ça ?",
                author: "Natasha", scene: 223, difficulty: 3 },
                { quote: "Vulgaire ? Tu trouves ça vulgaire ?",
                author: "Claudy", scene: 224, difficulty: 3 },
                { quote: "Le côté artistique c'est moi, donc je te demanderais de ne pas t'en mêler.",
                author: "Claudy", scene: 225, difficulty: 2 },
                { quote: "Je travaille en noir et blanc, moi, ici. Je suis obligé d'appuyer les couleurs, sinon ça va rendre fade.",
                author: "Claudy", scene: 226, difficulty: 1 },
                { quote: "Tu vois, ça tu ne sais pas parce que tu ne connais pas ça, toi.",
                author: "Claudy", scene: 227, difficulty: 3 },
                { quote: "Je vais te demander d'enlever le bas également.",
                author: "Claudy", scene: 228, difficulty: 2 },
                { quote: "Qu'est-ce qu'il y a 'non' ? Qu'est-ce qu'il y a 'non' !",
                author: "Claudy", scene: 229, difficulty: 3 },
                { quote: "Mais qu'est-ce que tu fous ici, ma fille ? Qu'est-ce que tu fous ?",
                author: "Claudy", scene: 230, difficulty: 3 },
                { quote: "Tu viens à une séance de photos de charme et tu veux rien retirer du tout ?",
                author: "Claudy", scene: 231, difficulty: 2 },
                { quote: "Je m'excuse, mais je ne pense pas t'avoir obligé à venir ici. Tu es quand même venue de ton propre gré.",
                author: "Claudy", scene: 232, difficulty: 2 },
                { quote: "Donc tu arrives ici et tu fais ta mijaurée. C'est très bien, mais on en reste là, alors.",
                author: "Claudy", scene: 233, difficulty: 2 },
                { quote: "Faut pas commencer à jouer avec mes couilles.",
                author: "Claudy", scene: 234, difficulty: 3 },
                { quote: "T'es tendue comme une crampe.",
                author: "Claudy", scene: 235, difficulty: 1 },
                { quote: "Mais non je suis pas tendue !",
                author: "Natasha", scene: 236, difficulty: 2 },
                { quote: "Si je te dis que t'es tendue, t'es tendue. C'est pas à toi de dire 'Je ne suis pas tendue'. Je dis t'es tendue, Natacha. C'est tout.",
                author: "Claudy", scene: 237, difficulty: 1 },
                { quote: "Il faut que tu te laisses venir vers moi... et je viendrais te chercher, t'inquiètes pas.",
                author: "Claudy", scene: 238, difficulty: 2 },
                { quote: "Pourquoi tu photographies que des adolescentes nues ?",
                author: "Natasha", scene: 239, difficulty: 2 },
                { quote: "Qu'est-ce qu'il y a ? Qu'est-ce que tu viens de dire maintenant ?! Tu répètes ce que tu viens de dire !",
                author: "Claudy", scene: 240, difficulty: 2 },
                { quote: "Est-ce que t'es à poil ? Est-ce que t'es nue ?",
                author: "Claudy", scene: 241, difficulty: 2 },
                { quote: "Tu sais que c'est grave ce que t'es occupée à faire. T'es occupée à me faire passer pour un pervers.",
                author: "Claudy", scene: 242, difficulty: 2 },
                { quote: "Moi je suis pas là pour me faire chier, ma fille. Je me fais déjà assez chier au boulot.",
                author: "Claudy", scene: 243, difficulty: 2 },
                { quote: "Moi je gagne ma vie suffisamment. Moi du pognon, j'en ai, t'inquiète pas pour moi. De ce côté-là tout va très bien.",
                author: "Claudy", scene: 244, difficulty: 3 },
                { quote: "Ah j'ai mis le doigt dessus, hein ? Toi t'es là pour les pépètes.",
                author: "Claudy", scene: 245, difficulty: 2 },
                { quote: "Mal baisée, va.",
                author: "Claudy", scene: 256, difficulty: 3 },
                { quote: "Allez penche-toi.",
                author: "Claudy", scene: 247, difficulty: 2 },
                { quote: "Je te demandais pas la lune.",
                author: "Claudy", scene: 248, difficulty: 3 },
                { quote: "Enlève ta petite culotte... enlève ta petite culotte. Tu veux que je le fasse ?",
                author: "Claudy", scene: 249, difficulty: 2 },
                { quote: "Et écarte un petit peu tes jambes, maintenant. Encore... encore... Ça c'est de trop.",
                author: "Claudy", scene: 250, difficulty: 2 },
                { quote: "Voilà. Et fais comme si t'étais amoureux de moi.",
                author: "Claudy", scene: 251, difficulty: 3 },
                { quote: "Maintenant ne bouge pas, je vais aller chercher le poney.",
                author: "Claudy", scene: 252, difficulty: 1 },
                { quote: "Eh ben t'as pas peur, toi. Quelle histoire, dis.",
                author: "JC", scene: 253, difficulty: 2 },
                { quote: "Ben c'est juste qu'il est un petit peu trop en rut à mon goût.",
                author: "Natasha", scene: 254, difficulty: 3 },
                { quote: "Et puis c'est pas ma faute si ce con est tombé amoureux de moi.",
                author: "Natasha", scene: 255, difficulty: 3 },
                { quote: "Et voilà. En cas de pépin, tu peux toujours m'appeler.",
                author: "JC", scene: 256, difficulty: 3 },
                { quote: "En tout cas celle-là elle sait dire merci.",
                author: "JC", scene: 257, difficulty: 2 },
                { quote: "Excusez-moi je... pensais à ça mais... vous vendez pas ça euh... comment ça s'appelle déjà ? La schnouff !",
                author: "Nadine", scene: 258, difficulty: 2 },
                { quote: "Parce qu'elle a une petite histoire de cœur, tout ça...",
                author: "Natasha", scene: 259, difficulty: 4 },
                { quote: "Donc je voulais juste te prévenir qu'on allait peut-être faire un petit peu de bruit...",
                author: "Natasha", scene: 260, difficulty: 3 },
                { quote: "Pourquoi... c'est une sauvage, non ? C'est ça ?",
                author: "Laurence", scene: 261, difficulty: 3 },
                { quote: "Genre tigresse, un peu ? Martinet, cuir, latex, gode à moteur ?",
                author: "Laurence", scene: 262, difficulty: 2 },
                { quote: "Je vous préviens, je vous prête pas mon king-kong, les filles.",
                author: "Laurence", scene: 263, difficulty: 2 },
                { quote: "Elle est dans son boudoir, elle fait la gueule.",
                author: "Laurence", scene: 264, difficulty: 3 },
                { quote: "Paraîtrait que je sens l'alcool quand je rentre du boulot.",
                author: "Laurence", scene: 265, difficulty: 3 },
                { quote: "Et la clope aussi, la cigarette, elle m'emmerde avec ça.",
                author: "Laurence", scene: 266, difficulty: 3 },
                { quote: "Tu sais ce qu'elle me dit ? 'J'ai l'impression de lécher un cendrier'.",
                author: "Laurence", scene: 267, difficulty: 2 },
                { quote: "L'autre avec sa cocaïne c'est mieux peut-être ?",
                author: "Laurence", scene: 268, difficulty: 3 },
                { quote: "C'est le monde à l'envers, il doit me trouver une gonzesse, c'est lui qui se la tape.",
                author: "Stef", scene: 269, difficulty: 2 },
                { quote: "Ah t'es là ?",
                author: "JC", scene: 270, difficulty: 5 },
                { quote: "Excuse-moi, j'ai eu un petit contretemps.",
                author: "JC", scene: 271, difficulty: 3 },
                { quote: "Bonjour Sabine.",
                author: "Autre", scene: 272, difficulty: 4 },
                { quote: "Eh quoi, on le fait ce match ?",
                author: "JC", scene: 273, difficulty: 3 },
                { quote: "Ben... la balle, elle t'attend, elle est comme moi.",
                author: "Stef", scene: 274, difficulty: 3 },
                { quote: "Et là tu vas m'attendre, parce que je suis en train de battre le Brésil, tu vois ?",
                author: "Stef", scene: 275, difficulty: 2 },
                { quote: "Dis-donc t'as fait vite, t'es venue en voiture ?",
                author: "Natasha", scene: 276, difficulty: 3 },
                { quote: "Oui dis la voiture de l'autre con, là.",
                author: "Nadine", scene: 277, difficulty: 3 },
                { quote: "Par contre pour trouver la marche arrière, je te dis pas.",
                author: "Nadine", scene: 278, difficulty: 2 },
                { quote: "Dis-donc, j'en reviens pas qu'il t'ai prêté sa bagnole...",
                author: "Natasha", scene: 279, difficulty: 2 },
                { quote: "Oh, je lui ai pas demandé son avis.",
                author: "Nadine", scene: 280, difficulty: 4 },
                { quote: "Bon, il y a quoi dans ton sac, là ?",
                author: "Natasha", scene: 281, difficulty: 4 },
                { quote: "Salle une, vos deux chiennes allemandes favorites Greta and Cynthia, accompagnées de leur berger... allemand lui aussi.",
                author: "Autre", scene: 282, difficulty: 2 },
                { quote: "Salle deux, Jonge meisjes op zwarte lange tisjen...",
                author: "Autre", scene: 283, difficulty: 3 },
                { quote: "C'est le coup de feu ici ou quoi ?",
                author: "JC", scene: 284, difficulty: 4 },
                { quote: "Nom de Dieu... regarde-moi ça l'état de cette cabine, dis.",
                author: "JC", scene: 285, difficulty: 2 },
                { quote: "C'est pas vrai...",
                author: "JC", scene: 286, difficulty: 5 },
                { quote: "Toi tu ne fais rien, là. Viens un peu ici avec ta raclette. Je vais te donner du travail, moi.",
                author: "JC", scene: 287, difficulty: 2 },
                { quote: "Tu trouves ça propre, toi ?",
                author: "JC", scene: 288, difficulty: 3 },
                { quote: "J'aime bien être un peu à mon aise, moi ici.",
                author: "JC", scene: 289, difficulty: 3 },
                { quote: "J'ai pas envie de me casser une jambe. C'est une vraie patinoire, ce truc.",
                author: "JC", scene: 290, difficulty: 2 },
                { quote: "Allez grouilles-toi, j'ai pas que ça à foutre.",
                author: "JC", scene: 291, difficulty: 4 },
                { quote: "Je vous préviens avec celle-là il faut du lubrifiant.",
                author: "Autre", scene: 292, difficulty: 3 },
                { quote: "Je ne m'appelle pas Arthur, mais... tu peux lui dire merci.",
                author: "JC", scene: 293, difficulty: 2 },
                { quote: "Ça m'étonne, mais j'ai pas réussi à m'achever avec cinquante euros.",
                author: "Claudy", scene: 294, difficulty: 2 },
                { quote: "Ça me fera des sous pour le parcmètre.",
                author: "Claudy", scene: 295, difficulty: 3 },
                { quote: "Elle était pas bien la blonde dans son micro-ondes ?",
                author: "JC", scene: 296, difficulty: 3 },
                { quote: "Je trouve que ça manque d'une touche de romantisme.",
                author: "Stef", scene: 297, difficulty: 3 },
                { quote: "Il te reste plus beaucoup de temps pour trouver la femme de ma vie.",
                author: "Stef", scene: 298, difficulty: 2 },
                { quote: "Parce que... tes promesses en l'air...",
                author: "Stef", scene: 299, difficulty: 4 },
                { quote: "Mais attends, ici c'est pour tirer ta crampe",
                author: "JC", scene: 300, difficulty: 3 },
                { quote: "Je t'avais tout de même à l’œil à l'intérieur. C'était un test.",
                author: "JC", scene: 301, difficulty: 3 },
                { quote: "Maintenant je vais pouvoir cibler la biche idéale.",
                author: "JC", scene: 302, difficulty: 3 },
                { quote: "Et oublie ce Peep-show une bonne fois pour toutes, dis.",
                author: "JC", scene: 303, difficulty: 3 },
                { quote: "Les amendes sont draconiennes",
                author: "Claudy", scene: 304, difficulty: 3 },
                { quote: "Petite illustration qui parlera plus qu'une explication.",
                author: "Claudy", scene: 305, difficulty: 3 },
                { quote: "Toujours à l'improviste deux fois par jour, c'est pas compliqué.",
                author: "Claudy", scene: 306, difficulty: 3 },
                { quote: "Un homme, Giovanni, n'avait pas son chapeau.",
                author: "Claudy", scene: 307, difficulty: 3 },
                { quote: "Mais c'est dehors, directement.",
                author: "Claudy", scene: 308, difficulty: 3 },
                { quote: "On commence pas à discuter 'oui, mais, bazar, je venais chercher mes clés...'",
                author: "Claudy", scene: 309, difficulty: 3 },
                { quote: "Il n'y a jamais rien à cette TV de merde !",
                author: "Autre", scene: 310, difficulty: 4 },
                { quote: "Il l'a déjà remplacée, ce saligaud.",
                author: "Sylvie", scene: 311, difficulty: 3 },
                { quote: "Et l'autre, là, a tout le physique d'une entraineuse.",
                author: "Sylvie", scene: 312, difficulty: 2 },
                { quote: "Il va quand même pas rester seul toute sa vie, ce crétin.",
                author: "Autre", scene: 313, difficulty: 3 },
                { quote: "Comme ça, elle lui vide une fois bien ses couilles, tiens.",
                author: "Autre", scene: 314, difficulty: 2 },
                { quote: "Alors là, je te trouve très, très distingué.",
                author: "Sylvie", scene: 315, difficulty: 3 },
                { quote: "Enfin de là à se taper la première pétasse venue...",
                author: "Sylvie", scene: 316, difficulty: 3 },
                { quote: "Pfff. Connasse.",
                author: "Autre", scene: 317, difficulty: 5 },
                { quote: "Ouh ! Attend... attend... mais il lui crache dessus ! Oh mais quelle violence.",
                author: "Sylvie", scene: 318, difficulty: 2 },
                { quote: "Et ce cinglé, là, il la tire par les cheveux, dis.",
                author: "Sylvie", scene: 319, difficulty: 2 },
                { quote: "Tire, seulement.",
                author: "Autre", scene: 320, difficulty: 3 },
                { quote: "Mais ça c'est l'alcool... l'alcool, hein mon petit ?",
                author: "Sylvie", scene: 321, difficulty: 3 },
                { quote: "C'est ça, ouais. L'alcool, tu connais pas toi.",
                author: "Autre", scene: 322, difficulty: 3 },
                { quote: "Ça je suis sûr qu'il l'a massacré.",
                author: "Sylvie", scene: 323, difficulty: 3 },
                { quote: "Qu'est-ce que tu veux que je te dise, moi ? Casse-lui les deux jambes.",
                author: "JC", scene: 324, difficulty: 3 },
                { quote: "Elle est déjà bien faite pour treize ans. Tu viendras me voir dans dix ans, toi.",
                author: "JC", scene: 325, difficulty: 3 },
                { quote: "Oh dis ! Si, il y a quelqu'un ! Miche, il a prit ta chaise, lui là.",
                author: "Autre", scene: 326, difficulty: 2 },
                { quote: "Eh ! Il y a pas assez de chaises ici ? Tu prends juste la mienne !",
                author: "Autre", scene: 327, difficulty: 2 },
                { quote: "Ouais allez, fais du vent, prends une autre, il y en a là-bas, il y en a une ici, tu me rends la mienne, okay ?!",
                author: "Autre", scene: 328, difficulty: 2 },
                { quote: "Faut surtout éviter les sales racistes dans ton genre, okay ?!",
                author: "JC", scene: 329, difficulty: 3 },
                { quote: "Allez, t'emmerde tout le monde avec ta chaise, là.",
                author: "Autre", scene: 330, difficulty: 3 },
                { quote: "Ça j'ai pas bien compris non plus. Qu'est-ce t'as dit connasse ?",
                author: "Autre", scene: 331, difficulty: 3 },
                { quote: "Le coup de boule du nouvel an t'a pas suffit ou quoi ? Je t'en mets directement un deuxième, c'est le même tarif...",
                author: "Autre", scene: 332, difficulty: 2 },
                { quote: "Eh mets un peu une Duvel, s'il te plaît.",
                author: "JC", scene: 333, difficulty: 4 },
                { quote: "Eh, le petit comique, là. Tu veux une bière ? Tu veux une bière ?",
                author: "Autre", scene: 334, difficulty: 3 },
                { quote: "Dis, il est toujours comme ça ton imbécile de mari à aboyer comme un Teckel ?",
                author: "JC", scene: 335, difficulty: 2 },
                { quote: "Tiens, prends déjà ça dans la gueule. Dikkenek !",
                author: "Autre", scene: 336, difficulty: 3 },
                { quote: "Ouais ça j'entends. Mets-ça plus fort !",
                author: "JC", scene: 337, difficulty: 4 },
                { quote: "Eh ! En tout cas ton copain ça va être sa fête. Il va le déglinguer !",
                author: "Autre", scene: 338, difficulty: 3 },
                { quote: "Je sais que je plais pas à tout le monde. Mais quand je vois à qui je plais pas, je me demande si ça me dérange vraiment.",
                author: "JC", scene: 339, difficulty: 2 },
                { quote: "Qu'est-ce qu'il y a ? Toujours occupée à tirer la gueule ? Avec moi il y a rien qui va de toute façon...",
                author: "Claudy", scene: 340, difficulty: 3 },
                { quote: "Dès que je fais mes photos elle tire la gueule, c'est pas compliqué.",
                author: "Claudy", scene: 341, difficulty: 2 },
                { quote: "C'est pas de la jalousie, mais ça y ressemble.",
                author: "Claudy", scene: 342, difficulty: 3 },
                { quote: "Ça ne marche pas ce machin-là.",
                author: "Autre", scene: 343, difficulty: 4 },
                { quote: "Elle a qu'à perdre vingt kilos, elle saura monter à pieds.",
                author: "Claudy", scene: 344, difficulty: 2 },
                { quote: "J'arrive, je te dis !",
                author: "Claudy", scene: 345, difficulty: 3 },
                { quote: "Je deviens fou, moi !",
                author: "Claudy", scene: 346, difficulty: 3 },
                { quote: "J'ai déjà dit vingt fois, faut foutre le choke. C'est bon, c'est parti.",
                author: "Claudy", scene: 347, difficulty: 2 },
                { quote: "Tu n'aurais pas l'heure s'il te plait ?",
                author: "Claudy", scene: 348, difficulty: 4 },
                { quote: "Voilà, moi en fait, en deux mots je suis photographe, je cherches des modèles...",
                author: "Claudy", scene: 349, difficulty: 2 },
                { quote: "Tu as mon numéro ici, si ça t'intéresse...",
                author: "Claudy", scene: 350, difficulty: 3 },
                { quote: "Moi ça pourrait m'intéresser. Tiens, tu prends.",
                author: "Claudy", scene: 351, difficulty: 3 },
                { quote: "Petit cul. Ah les flamands. Pour une fois qu'il y a une flamande bien gaulée...",
                author: "Claudy", scene: 352, difficulty: 2 },
                { quote: "Voilà. Ça a de la gueule. J'espère que le poisson morde. Mademoiselle.",
                author: "Claudy", scene: 353, difficulty: 3 },
                { quote: "C'est bien payé vos trucs ?",
                author: "Fabienne", scene: 354, difficulty: 4 },
                { quote: "Ça dépend de toi ça, ma cocotte.",
                author: "Claudy", scene: 355, difficulty: 3 },
                { quote: "Ça veut dire quoi ça 'un livre sur les rapports entre les femmes et les animaux' ?",
                author: "Fabienne", scene: 356, difficulty: 2 },
                { quote: "Ça veut dire exactement ce que ça veut dire.",
                author: "Claudy", scene: 357, difficulty: 3 },
                { quote: "C'est un livre qui parle du rapport qui peut exister entre un animal d'une part, et une femme de l'autre part.",
                author: "Claudy", scene: 358, difficulty: 2 },
                { quote: "Mais, c'est pas des photos à caractère sexuel...",
                author: "Fabienne", scene: 359, difficulty: 3 },
                { quote: "Ecoute ma fille, si ça t'intéresse, tu as mon numéro qui est là, si ça t'intéresse pas, au revoir merci et bon week-end.",
                author: "Claudy", scene: 360, difficulty: 2 },
                { quote: "M'enfin il y a moyen que moi je... tu vois ?",
                author: "Fabienne", scene: 361, difficulty: 4 },
                { quote: "Il y a moyen de tout. Tout est négociable, je te dis, il n'y a pas un plan tarifaire avec les prix.",
                author: "Claudy", scene: 362, difficulty: 2 },
                { quote: "Est-ce que t'es épilée, t'es pas épilée... est-ce que t'as des copines, t'as pas de copines...",
                author: "Claudy", scene: 363, difficulty: 2 },
                { quote: "En tout cas ils t'ont pas loupée, je sais pas si c'est un cheval ou une truie...",
                author: "Claudy", scene: 364, difficulty: 2 },
                { quote: "T'as vu ta tronche ou quoi ? On peut aussi faire un bouquin sur Halloween si tu veux...",
                author: "Claudy", scene: 365, difficulty: 2 },
                { quote: "Connard, va !",
                author: "Fabienne", scene: 366, difficulty: 4 },
                { quote: "Eh ! Va te faire refaire, Alien !",
                author: "Claudy", scene: 367, difficulty: 2 },
                { quote: "Vous avez de la chance qu'elle a dégagé, tiens... elle prenait un coup d'agrafeuse dans sa gueule.",
                author: "Claudy", scene: 368, difficulty: 3 },
                { quote: "En vérité, mon mari est un peu abonné à ce genre d'histoires. On a eu un truc comme ça déjà à Palma de Majorque.",
                author: "Autre", scene: 369, difficulty: 3 },
                { quote: "Oh j'adore Palma. J'adore le Portugal.",
                author: "Laurence", scene: 370, difficulty: 3 },
                { quote: "Mais ici... ben il l'a saigné comme un cochon.",
                author: "Autre", scene: 371, difficulty: 3 },
                { quote: "Et encore heureux que mon mari n'était pas armé.",
                author: "Autre", scene: 372, difficulty: 3 },
                { quote: "Procédure classique, quoi.",
                author: "Laurence", scene: 373, difficulty: 5 },
                { quote: "Bien bronzé, quoi...",
                author: "Laurence", scene: 374, difficulty: 3 },
                { quote: "J'ai rien dit ! J'ai rien dit.",
                author: "Laurence", scene: 375, difficulty: 5 },
                { quote: "Merde alors, c'est quoi ça maintenant à nouveau ?",
                author: "Nadine", scene: 376, difficulty: 3 },
                { quote: "C'est pas les batteries, t'as pas laissé les phares allumés ?",
                author: "Natasha", scene: 377, difficulty: 2 },
                { quote: "Dis, je suis pas assez conne pour allumer les phares en plein jour.",
                author: "Nadine", scene: 378, difficulty: 3 },
                { quote: "Le moteur c'est pas devant ?",
                author: "Natasha", scene: 379, difficulty: 3 },
                { quote: "Evidemment que non, sur les bagnoles de sport le moteur c'est toujours à l'arrière, le moteur.",
                author: "Nadine", scene: 380, difficulty: 2 },
                { quote: "Ceci dit, sur ce modèle-là c'est peut-être à l'avant.",
                author: "Nadine", scene: 381, difficulty: 3 },
                { quote: "Tu vas pas me croire mais il y a pas de moteur là non plus.",
                author: "Nadine", scene: 382, difficulty: 3 },
                { quote: "Bon Dieu, ce téléphone, merde ! Putain... Allo ?",
                author: "JC", scene: 383, difficulty: 4 },
                { quote: "Je te dérange ?",
                author: "Natasha", scene: 384, difficulty: 5 },
                { quote: "C'est fou parce que... je pensais justement à toi, tiens.",
                author: "JC", scene: 385, difficulty: 3 },
                { quote: "Dis-moi... tu t'y connais en mécanique et en moteurs ?",
                author: "Natasha", scene: 386, difficulty: 3 },
                { quote: "Les moteurs, moi je les démonte et je les remonte les yeux fermés. Et au passage, je te fais l'entretien.",
                author: "JC", scene: 387, difficulty: 2 },
                { quote: "En tout cas, toi les voitures c'est pas ton truc, hein poupée ?",
                author: "JC", scene: 388, difficulty: 2 },
                { quote: "Ouais je vois... on m'a déjà eu comme ça... pour un déménagement. Bon allez, je vais être sympa. T'es où ?",
                author: "JC", scene: 389, difficulty: 2 },
                { quote: "Ça va ? C'est pas trop dur comme boulot ?",
                author: "Autre", scene: 390, difficulty: 3 },
                { quote: "Dis... si tu veux ramasser des balles... tu peux toujours aller à Roland-Garros, je connais bien le big boss là-bas.",
                author: "Autre", scene: 391, difficulty: 2 },
                { quote: "Je suis obligé de renvoyer les balles... sinon je peux pas tondre.",
                author: "Stef", scene: 392, difficulty: 2 },
                { quote: "Ouais... je suis en train de lire un livre sur le licenciement. Je suis au chapitre deux et j'ai déjà tout compris.",
                author: "Autre", scene: 393, difficulty: 3 },
                { quote: "Il est con celui-là... il est vraiment con celui-là.",
                author: "Autre", scene: 394, difficulty: 4 },
                { quote: "Tiens, arrête maintenant. Tu sais quoi ? T'es vraiment trop nul, t'es archi-nul.",
                author: "Autre", scene: 395, difficulty: 3 },
                { quote: "Tu es viré de chez viré. Tu es né idiot, tu vas mourir idiot.",
                author: "Autre", scene: 396, difficulty: 2 },
                { quote: "Tu me casse les couilles, tu fous rien. Allez dégage, casse-toi.",
                author: "Autre", scene: 397, difficulty: 2 },
                { quote: "Attends, tes merdes ici. Oublie rien, allez dégage ! Connard. Casse-toi ! Allez. Je veux plus jamais te voir, dégage.",
                author: "Autre", scene: 398, difficulty: 2 },
                { quote: "Quel klette ce pei... trou du cul de merde...",
                author: "Autre", scene: 399, difficulty: 3 },
                { quote: "Ben... on trouve plus le moteur.",
                author: "Nadine", scene: 400, difficulty: 3 },
                { quote: "Le moteur oui, je vois. T'inquiète pas je m'y connais, tsé.",
                author: "JC", scene: 401, difficulty: 2 },
                { quote: "Qu'est-ce qu'il fait ton mari ? Faut déjà avoir les moyens pour acheter ça, dis.",
                author: "JC", scene: 402, difficulty: 2 },
                { quote: "Il est peut-être dans la boite à gants...",
                author: "JC", scene: 403, difficulty: 2 },
                { quote: "Tu veux pas faire du topless ? Tu viens pas avec nous ? Fais pas la gênée...",
                author: "JC", scene: 404, difficulty: 2 },
                { quote: "J'ai jamais fait ça moi... mais j'ai jamais fait ça moi.",
                author: "Nadine", scene: 405, difficulty: 3 },
                { quote: "Oh lala... Vite ! Fait quelque chose, faut que tu bouges, là.",
                author: "Natasha", scene: 406, difficulty: 3 },
                { quote: "Si elle te voit, elle te tue, elle me tue et elle se tue après...",
                author: "Natasha", scene: 407, difficulty: 2 },
                { quote: "Tout ça à cause d'un mobile home qui s'est retourné juste devant nous. Oh tu verrais le truc, il reste plus rien.",
                author: "Sylvie", scene: 408, difficulty: 3 },
                { quote: "Ils sont tous morts, un vrai barbecue.",
                author: "Sylvie", scene: 409, difficulty: 3 },
                { quote: "Monsieur ? Monsieur... vous voulez qu'on mette un matelas, non ? Eh c'est quoi ce jeu ? On peut jouer ?",
                author: "Laurence", scene: 410, difficulty: 2 },
                { quote: "Il est costaud, attends... combien de temps il va tenir ce con là ?",
                author: "Laurence", scene: 411, difficulty: 3 },
                { quote: "Ça sent un peu la salle de Mini-Foot ici, faut aérer...",
                author: "Sylvie", scene: 412, difficulty: 3 },
                { quote: "Et un de ces quatre, je vais t'envoyer ma petite polonaise...",
                author: "Sylvie", scene: 413, difficulty: 3 },
                { quote: "Attends mon petit chouchou, délivre-moi d'un doute... c'est quand même pas toi qui a avalé tout ça ?",
                author: "Sylvie", scene: 414, difficulty: 2 },
                { quote: "Ah non ça j'avale pas.",
                author: "Natasha", scene: 415, difficulty: 4 },
                { quote: "Non mais eh... tu les connais, toi, ces drôles de filles là ? Elles sont toujours ensemble, je suis sûr que c'est des gouines.",
                author: "Sylvie", scene: 416, difficulty: 2 },
                { quote: "Ouais, prend le pouf plutôt. Pas le vert ! Il est moche...",
                author: "Laurence", scene: 417, difficulty: 2 },
                { quote: "Prend celui qu'on a ramené du Sahel... euh d'Israël... c'est pareil.",
                author: "Laurence", scene: 418, difficulty: 3 },
                { quote: "Ah oui, celui qu'on avait volé, là...",
                author: "Autre", scene: 419, difficulty: 5 },
                { quote: "Qu'on a volé... que t'as volé. Oh l'autre !",
                author: "Laurence", scene: 420, difficulty: 2 },
                { quote: "Ah mais moi, je supporte pas les lesbiennes. Rien qu'à les voir, j'ai les poils qui s'irisent.",
                author: "Sylvie", scene: 421, difficulty: 2 },
                { quote: "Oh attends, il y en a un qui court tout nu dans l'herbe... il est comme toi, il cherche son slip...",
                author: "Sylvie", scene: 422, difficulty: 2 },
                { quote: "Excusez-moi j'ai oublié mon calbar...",
                author: "JC", scene: 423, difficulty: 3 },
                { quote: "Dis-donc j'y pense là... on a pas oublié ton anniv' ?",
                author: "Sylvie", scene: 424, difficulty: 3 },
                { quote: "Oh mais en ce moment on court partout, comme des fous, toujours entre deux jets, dix mille trucs à faire...",
                author: "Sylvie", scene: 425, difficulty: 3 },
                { quote: "Non mais je te jure, on croirait vraiment qu'il y a un avion qui s'est écrasé là-dedans. Incroyable.",
                author: "Sylvie", scene: 426, difficulty: 3 },
                { quote: "Regarde-moi ça, dis...",
                author: "JC", scene: 427, difficulty: 4 },
                { quote: "Dis, je t'ai déjà parlé de la copine de Natacha ? Nadine. Elle vient de quitter son mari.",
                author: "JC", scene: 428, difficulty: 2 },
                { quote: "Allez, lève-toi, debout. Debout ! Il faut se réveiller, fieu.",
                author: "JC", scene: 429, difficulty: 2 },
                { quote: "Avec ton air de chien battu, là. Faut que tu arrêtes de subir la vie, d'être une victime en permanence...",
                author: "JC", scene: 430, difficulty: 2 },
                { quote: "Nom de Dieu, le soleil il se lève avec ou sans toi, tu te lèves pas il en a rien à foutre ! Et personne en a rien à foutre !",
                author: "JC", scene: 431, difficulty: 2 },
                { quote: "Oui, ben ça va ! Ça va, je me lève...",
                author: "Stef", scene: 432, difficulty: 3 },
                { quote: "Et enlève-moi ce vilain calbar.",
                author: "JC", scene: 433, difficulty: 2 },
                { quote: "Faut pas me prendre pour un con.",
                author: "JC", scene: 434, difficulty: 4 },
                { quote: "Ouais, c'est ça... il y a pas marqué 'assistant social', ici.",
                author: "JC", scene: 435, difficulty: 2 },
                { quote: "Bonjour Madame... je peux m'assoir ?",
                author: "Aziz", scene: 436, difficulty: 3 },
                { quote: "En fait, je viens vous voir pour mon mot, là... pour mon certificat pour l'école.",
                author: "Aziz", scene: 437, difficulty: 3 },
                { quote: "Vous vous rappelez l'autre jour... soi-disant j'avais volé la platine avec l'autre...",
                author: "Aziz", scene: 438, difficulty: 3 },
                { quote: "Ah ouais... t'es une sacrée teigne, toi.",
                author: "Laurence", scene: 439, difficulty: 3 },
                { quote: "Tu m'as l'air honnête, j'aime bien ta gueule. T'as de la chance, je vais te le faire ton mot.",
                author: "Laurence", scene: 440, difficulty: 2 },
                { quote: "Bon alors 'Je soussignée'... soussignée 'ée'. Féminin pluriel.",
                author: "Laurence", scene: 441, difficulty: 2 },
                { quote: "Ça si t'irait à l'école, tu le saurais par exemple.",
                author: "Laurence", scene: 442, difficulty: 3 },
                { quote: "Le 12, je le savais, ...à douze heures douze. Voilà, comme ça ça rime.",
                author: "Laurence", scene: 443, difficulty: 2 },
                { quote: "Et cetera, et cetera... on va y mettre les formes...",
                author: "Laurence", scene: 444, difficulty: 3 },
                { quote: "Non mais c'est bon, c'est des potes à moi, je les connais, tranquille...",
                author: "Aziz", scene: 445, difficulty: 3 },
                { quote: "T'es obligé de te déplacer avec toute ta bande, là ?",
                author: "Laurence", scene: 446, difficulty: 3 },
                { quote: "Il m'énerve, mais je l'aime bien. Allez dégage. Hop !",
                author: "Laurence", scene: 447, difficulty: 3 },
                { quote: "T'as une bonne gueule en ce moment, qu'est-ce qui se passe ?",
                author: "Laurence", scene: 448, difficulty: 3 },
                { quote: "J'ai rencontré une fille...",
                author: "Aziz", scene: 449, difficulty: 4 },
                { quote: "Oui. En plus, elle a une de ces villas...",
                author: "Aziz", scene: 450, difficulty: 2 },
                { quote: "Tu l'aimes pour sa villa ou pour elle ?",
                author: "Laurence", scene: 451, difficulty: 2 },
                { quote: "Tiens, tu lui offres des cailloux, tu fais un cœur dessus, elle est contente.",
                author: "Laurence", scene: 452, difficulty: 2 },
                { quote: "Mais bien sûr, mais les femmes il faut leur mentir.",
                author: "Laurence", scene: 453, difficulty: 4 },
                { quote: "Je l'aime bien, ce con. Il m'énerve avec sa tête de con, mais...",
                author: "Laurence", scene: 454, difficulty: 3 },
                { quote: "Allo ? Oui ? A qui ai-je l'honneur ?",
                author: "Claudy", scene: 455, difficulty: 3 },
                { quote: "Faut vous présenter parce que... vous n'êtes pas la seule cliente que j'ai, si je peux ainsi m'exprimer.",
                author: "Claudy", scene: 456, difficulty: 2 },
                { quote: "Vous savez, il est dix-sept heures quarante-cinq partout en Belgique, on aimerait bien aussi avoir un petit bout de week-end.",
                author: "Claudy", scene: 457, difficulty: 2 },
                { quote: "Vous auriez téléphoné dix minutes plus tôt, je savais encore faire quelque chose",
                author: "Claudy", scene: 458, difficulty: 3 },
                { quote: "Pour ne rien vous cacher on est occupé à boire un verre.",
                author: "Claudy", scene: 459, difficulty: 3 },
                { quote: "Qu'est-ce qui reste en porc, en vivant je veux parler...",
                author: "Claudy", scene: 460, difficulty: 2 },
                { quote: "Le petit qui est arrivé malade au matin, tu l'as toujours ?",
                author: "Claudy", scene: 461, difficulty: 3 },
                { quote: "Je sais comment faire... je vais vous mettre une bête vivante, et une bête décédée.",
                author: "Claudy", scene: 462, difficulty: 2 },
                { quote: "La vivante... je l'égorgerai sur place s'il le faut, et la décédée ça je facture d'office.",
                author: "Claudy", scene: 463, difficulty: 2 },
                { quote: "Ok, je serai en civil, donc je répète, je ne décharge pas.",
                author: "Claudy", scene: 464, difficulty: 3 },
                { quote: "Et c'est quarante kilos, une bestiole comme ça, faut pas un gringalet.",
                author: "Claudy", scene: 465, difficulty: 2 },
                { quote: "Tout ce que je sais, c'est que c'est une pétasse qui me fait chier, une péteuse... tsé.",
                author: "Claudy", scene: 466, difficulty: 3 },
                { quote: "T'as des gens comme ça, ils croient que la terre entière leur tourne autour...",
                author: "Claudy", scene: 467, difficulty: 3 },
                { quote: "Mais elle va payer, ça je peux te le dire.",
                author: "Claudy", scene: 468, difficulty: 4 },
                { quote: "Je suis bête... je t'envoie un SMS et t'es à côté de moi.",
                author: "Fabienne", scene: 469, difficulty: 2 },
                { quote: "T'es con ou quoi ? Je t'ai dit qu'on me l'avait volé mon portable.",
                author: "Greg", scene: 470, difficulty: 2 },
                { quote: "On m'appelait trop souvent... j'ai plus de vie privée.",
                author: "Greg", scene: 471, difficulty: 3 },
                { quote: "Oh ! Tu crois que t'es tout seul sur la route, gros con ?",
                author: "Greg", scene: 472, difficulty: 3 },
                { quote: "Ça va... ça sert à rien de s'énerver, ce gars-là il va quand même pas jumper au-dessus de la voiture de devant...",
                author: "Fabienne", scene: 473, difficulty: 3 },
                { quote: "Bon tu peux te taire s'il te plaît ?",
                author: "Greg", scene: 474, difficulty: 4 },
                { quote: "Tu sais très bien que je ne supporte pas que tu parles quand je conduis.",
                author: "Greg", scene: 475, difficulty: 3 },
                { quote: "Oh dégage... allez hop ! Allez c'est moi le king de la route ici.",
                author: "Greg", scene: 476, difficulty: 2 },
                { quote: "T'es prêt à prendre ta raclée ?",
                author: "JC", scene: 477, difficulty: 3 },
                { quote: "Allez coupe-moi ça, tu sais bien que ça me rend agressif.",
                author: "JC", scene: 478, difficulty: 4 },
                { quote: "Eh, c'est une certaine Fabienne qui m'invite au Zoute pour son anniv'...",
                author: "Stef", scene: 479, difficulty: 3 },
                { quote: "J'avais complètement oublié cette conne, là. Fabienne...",
                author: "JC", scene: 480, difficulty: 2 },
                { quote: "On va encore écouter de la musique de supermarché, remixée par des grosses tapettes...",
                author: "JC", scene: 481, difficulty: 2 },
                { quote: "Tu demanderais pas à ta femme de venir avec sa copine ?",
                author: "Stef", scene: 482, difficulty: 4 },
                { quote: "Je vais te faire plaisir, tu sais ? On va y aller à la mer. Mais d'abord je vais te donner un cours de drague assez poussé, tu vois ?",
                author: "JC", scene: 483, difficulty: 2 },
                { quote: "Ça va du point A au point G.",
                author: "JC", scene: 484, difficulty: 1 },
                { quote: "Faut pas essayer à tout prix d'être original, tu vois ? Ta tête est déjà originale. Faut pas surenchérir, tu comprends ?",
                author: "JC", scene: 485, difficulty: 2 },
                { quote: "Quand tu lui parles, évite de négocier avec ses nichons.",
                author: "JC", scene: 486, difficulty: 3 },
                { quote: "C'est un truc que j'ai déjà expérimenté, ça s'appelle 'tomber de son sus'.",
                author: "JC", scene: 487, difficulty: 2 },
                { quote: "De toute façon, ta tête n'est jamais qu'à un mètre du sol. Tu risques pas de te faire mal.",
                author: "JC", scene: 488, difficulty: 3 },
                { quote: "Tiens, va t'occuper du connard là, putain.",
                author: "Laurence", scene: 489, difficulty: 4 },
                { quote: "Elle est pas mal la voiture.",
                author: "Laurence", scene: 490, difficulty: 4 },
                { quote: "Les voitures de sport... c'est un peu compliqué pour sortir.",
                author: "Greg", scene: 491, difficulty: 2 },
                { quote: "Ouais... vous avez une pièce d'identité, jeune homme ?",
                author: "Laurence", scene: 492, difficulty: 2 },
                { quote: "Non, non... j'en vois mille des comme toi par jour, donc on se connait pas. Ok ?",
                author: "Laurence", scene: 493, difficulty: 3 },
                { quote: "J'aurais jamais cru que j'ai bu autant de bière...",
                author: "Claudy", scene: 494, difficulty: 3 },
                { quote: "Minute, papillon. Je termine. On se calme. Je suis mal garé ?",
                author: "Claudy", scene: 495, difficulty: 2 },
                { quote: "Vous savez à combien vous rouliez, là ?",
                author: "Laurence", scene: 496, difficulty: 2 },
                { quote: "Ah non, ben... je regarde jamais le compteur. Avec ces engins, ça trace. J'imagine... deux cents ?",
                author: "Greg", scene: 497, difficulty: 2 },
                { quote: "Je vous ai pas vu, je vous dis que je vous ai pas vu. Si je vous vois, je pile sur mes freins...",
                author: "Claudy", scene: 498, difficulty: 2 },
                { quote: "Les connexions se font...",
                author: "Claudy", scene: 499, difficulty: 3 },
                { quote: "Je viens d'acheter mon... de passer mon permis.",
                author: "Fabienne", scene: 500, difficulty: 3 },
                { quote: "Eh ben vous allez commencer la pratique tout de suite.",
                author: "Laurence", scene: 501, difficulty: 3 },
                { quote: "Ah non mais moi, les femmes au volant ça me...",
                author: "Greg", scene: 502, difficulty: 3 },
                { quote: "Tu te tais ! Tais-toi.",
                author: "Laurence", scene: 503, difficulty: 5 },
                { quote: "Faut bien un bon arrangement qu'un mauvais procès, comme on dit.",
                author: "Claudy", scene: 504, difficulty: 3 },
                { quote: "De là à se faire plumer par un poulet, ça devient autre chose... en vous remerciant.",
                author: "Claudy", scene: 505, difficulty: 3 },
                { quote: "Eh, tu arrêtes avec ta patte dans mon siège, s'il te plaît.",
                author: "Claudy", scene: 506, difficulty: 3 },
                { quote: "On voit bien le pognon. C'est pas une baraque ce truc, c'est un centre de vacances. Comme dans les films.",
                author: "Claudy", scene: 507, difficulty: 3 },
                { quote: "Eh ! Tu ne me vois pas ? Tu ne me vois pas ? Ouhou !",
                author: "Claudy", scene: 508, difficulty: 2 },
                { quote: "Faut pas tirer la gueule, je te dis, s'ils ne sont pas deux cents tu reviens avec moi. C'est tout ça s'arrête là.",
                author: "Claudy", scene: 509, difficulty: 2 },
                { quote: "Tu es en supplément. Tu es en supplément, une sécurité c'est tout.",
                author: "Claudy", scene: 510, difficulty: 2 },
                { quote: "On est des grands professionnels, c'est tout.",
                author: "Claudy", scene: 511, difficulty: 3 },
                { quote: "Allez viens. Allez viens. Ne fais pas ça... on n'a aucune allure. Ça n'a aucune allure, allez.",
                author: "Claudy", scene: 512, difficulty: 2 },
                { quote: "Je suis désolé... il n'y a pas de 'tchu-tchu-tchu' c'est comme ça. C'est comme ça.",
                author: "Claudy", scene: 513, difficulty: 3 },
                { quote: "Reste près de moi, je ne sais même pas moi-même où je dois aller.",
                author: "Claudy", scene: 514, difficulty: 2 },
                { quote: "Goal ! Reste là, toi. Non mais ! Tu vas te calmer, toi ? Sale moucheron.",
                author: "Greg", scene: 515, difficulty: 3 },
                { quote: "Tu vas me retourner dans ta caravane, sale Manouche.",
                author: "Greg", scene: 516, difficulty: 4 },
                { quote: "C'est qui le king de la beach ici ?",
                author: "Greg", scene: 517, difficulty: 2 },
                { quote: "Ouh, il est mignon le petit cochon. C'est un vrai ?",
                author: "Fabienne", scene: 518, difficulty: 3 },
                { quote: "Non c'est un électrique.",
                author: "Claudy", scene: 519, difficulty: 4 },
                { quote: "Ça fait deux heures que je tourne, moi ici dans le quartier.",
                author: "Claudy", scene: 520, difficulty: 3 },
                { quote: "C'est une affaire qui roule ? Enfin je veux dire... t'es amoureuse ?",
                author: "Nadine", scene: 521, difficulty: 3 },
                { quote: "Qu'est-ce que tu lui trouves à ce type ? Quand même c'est pas un playboy...",
                author: "Nadine", scene: 522, difficulty: 3 },
                { quote: "Quand même, c'est une grande gueule.",
                author: "Nadine", scene: 523, difficulty: 4 },
                { quote: "Il a toujours plein de fric et il travaille pas. Me dis pas que c'est un voleur.",
                author: "Nadine", scene: 524, difficulty: 3 },
                { quote: "Mais non. Il prend l'argent là où il y en a.",
                author: "Natasha", scene: 525, difficulty: 3 },
                { quote: "Loués, non, volés oui.",
                author: "Nadine", scene: 526, difficulty: 3 },
                { quote: "Allez ! Tchin, et tu te détends maintenant.",
                author: "Natasha", scene: 527, difficulty: 3 },
                { quote: "Mais je ne fais que ça, me détendre.",
                author: "Nadine", scene: 528, difficulty: 3 },
                { quote: "Non, commence pas avec tes trucs à quatre...",
                author: "Nadine", scene: 529, difficulty: 2 },
                { quote: "C'est vrai qu'il est gentil, mais c'est pas du tout mon type.",
                author: "Nadine", scene: 530, difficulty: 3 },
                { quote: "Si j'avais su j'aurais pris mon maillot.",
                author: "Claudy", scene: 531, difficulty: 4 },
                { quote: "A l'aise.",
                author: "Aziz", scene: 532, difficulty: 5 },
                { quote: "Bonjour. J'ai envie de te sucer. C'est par là.",
                author: "Fabienne", scene: 533, difficulty: 3 },
                { quote: "Nom de Dieu. Quel gâchis. Quand je pense que ce mec va foutre ses paluches sur ce cul-là. Ça me rend malade, ça.",
                author: "Autre", scene: 534, difficulty: 3 },
                { quote: "Très beau corps. Montre... Je suis curieux de voir ce qu'il y a en-dessous de la culotte.",
                author: "Claudy", scene: 535, difficulty: 2 },
                { quote: "J'ai du pognon, c'est fait pour voir des choses.",
                author: "Claudy", scene: 536, difficulty: 3 },
                { quote: "Voilà votre homme, est-ce que tu peux aider monsieur à décharger le cochon ?",
                author: "Fabienne", scene: 537, difficulty: 3 },
                { quote: "Quel cochon ?",
                author: "Greg", scene: 538, difficulty: 4 },
                { quote: "Ben le cochon ! Oh débrouilles-toi.",
                author: "Fabienne", scene: 539, difficulty: 3 },
                { quote: "C'est toi qui va décharger le cochon ?",
                author: "Claudy", scene: 540, difficulty: 2 },
                { quote: "T'es épais comme un câble de frein à main.",
                author: "Claudy", scene: 541, difficulty: 2 },
                { quote: "Il est où le cochon ?",
                author: "Greg", scene: 542, difficulty: 3 },
                { quote: "Dans la Celica, dans ma voiture, la Celica jaune. Quand tu rentres à ma gauche, le cochon est dans le coffre.",
                author: "Claudy", scene: 543, difficulty: 2 },
                { quote: "J'ai demandé une bière, pas un Mozart. T'as dix centilitres là-dedans.",
                author: "Claudy", scene: 544, difficulty: 2 },
                { quote: "Nom de Dieu de merde ! Oh merde, ma mère va me tuer.",
                author: "Greg", scene: 545, difficulty: 3 },
                { quote: "Je le met où ce cochon ?",
                author: "Greg", scene: 546, difficulty: 3 },
                { quote: "J'adore son odeur. C'est un peu comme la nuque des bébés.",
                author: "Stef", scene: 547, difficulty: 3 },
                { quote: "Je suis quand même un peu stressé pour ce soir, moi.",
                author: "Stef", scene: 548, difficulty: 3 },
                { quote: "Mais arrête avec tes raisonnements alchimistes... les sept points tu les connais sur le bout des ongles.",
                author: "JC", scene: 549, difficulty: 2 },
                { quote: "C'est toi Fabienne alors ?",
                author: "Stef", scene: 550, difficulty: 4 },
                { quote: "Bah bon anniversaire, alors.",
                author: "Stef", scene: 551, difficulty: 4 },
                { quote: "Vous devriez prendre des asperges.",
                author: "Fabienne", scene: 552, difficulty: 5 },
                { quote: "T'es con ou quoi ?",
                author: "Greg", scene: 553, difficulty: 4 },
                { quote: "Je suis désolé mais je ne supporte pas qu'on me touche les seins !",
                author: "Nadine", scene: 554, difficulty: 2 },
                { quote: "Mais ça va... c'est que des seins ! Putain, je pisse le sang.",
                author: "Greg", scene: 555, difficulty: 2 },
                { quote: "Oh ! Bonsoir. On peut savoir ce que vous fabriquez là-haut, s'il vous plaît ?",
                author: "Autre", scene: 556, difficulty: 2 },
                { quote: "Disons que je fais une photo de l'éclipse, ils m'ont dit qu'on verrai les étoiles.",
                author: "Claudy", scene: 557, difficulty: 2 },
                { quote: "Dis, je te signale quand même juste que la lune est derrière toi là-bas.",
                author: "Autre", scene: 558, difficulty: 2 },
                { quote: "Mais quelle agressivité, oh. Du calme, j'ai rien fait de mal.",
                author: "Claudy", scene: 559, difficulty: 2 },
                { quote: "Je suis cool, fieu.",
                author: "Autre", scene: 560, difficulty: 5 },
                { quote: "Il y a pas eu attouchement.",
                author: "Claudy", scene: 561, difficulty: 3 },
                { quote: "Qu'est-ce que t'attends, toi ? T'attends qu'elle se fasse accoster par un pedzouille ou quoi ?",
                author: "JC", scene: 562, difficulty: 2 },
                { quote: "Si tu veux arriver au point G, va falloir mouiller ton maillot.",
                author: "JC", scene: 563, difficulty: 2 },
                { quote: "Je l'aime pas du tout, je te l'ai déjà dit. On dirait qu'il a toujours la grippe, ce type.",
                author: "Nadine", scene: 564, difficulty: 2 },
                { quote: "Quand il parle, on entends plus que les consonnes.",
                author: "Nadine", scene: 565, difficulty: 3 },
                { quote: "Je ne l'ai jamais vu sans un verre à la main, regarde-le.",
                author: "Nadine", scene: 566, difficulty: 3 },
                { quote: "Tu sais que t'es bien roulée ?",
                author: "JC", scene: 567, difficulty: 3 },
                { quote: "Bon, eh bien je vais aller retrouver mon homme... qui sympathise avec une pute.",
                author: "Natasha", scene: 568, difficulty: 2 },
                { quote: "Coin coin !",
                author: "Stef", scene: 569, difficulty: 3 },
                { quote: "Mon pauvre ami, tu t'es vu quand t'as bu ?",
                author: "Nadine", scene: 570, difficulty: 3 },
                { quote: "Oh putain ! Il l'a fait, il l'a fait.",
                author: "JC", scene: 571, difficulty: 3 },
                { quote: "Qu'est-ce qu'elle attend, elle ? Mais jette-toi à l'eau, toi.",
                author: "JC", scene: 572, difficulty: 2 },
                { quote: "Au revoir... j'ai passé une très bonne soirée. Tu voudrais pas m'embrasser ?",
                author: "Nadine", scene: 573, difficulty: 3 },
                { quote: "Je voulais savoir si tu voulais bien m'embrasser parce que... moi j'ai très envie de t'embrasser.",
                author: "Nadine", scene: 574, difficulty: 2 },
                { quote: "Ecoute... t'as été victime de quinze agressions ces trois dernières semaines.",
                author: "Laurence", scene: 575, difficulty: 2 },
                { quote: "T'as été attaqué successivement par un psychopathe, des gosses de riches, bref... un véritable acharnement national.",
                author: "Laurence", scene: 576, difficulty: 2 },
                { quote: "Je pense qu'il serait temps que tu te remettes un tout petit peu en question.",
                author: "Laurence", scene: 577, difficulty: 3 },
                { quote: "Voilà, parce que tout le monde s'accorde à dire que peut-être ce serait un tout petit peu de ta faute.",
                author: "Laurence", scene: 578, difficulty: 3 },
                { quote: "Je vais donc te donner les coordonnées d'un ami qui est psychologue...",
                author: "Laurence", scene: 579, difficulty: 4 },
                { quote: "Je peux voir ma maman ?",
                author: "Greg", scene: 580, difficulty: 3 },
                { quote: "Et puis change de coupe peut-être aussi parce que ça c'est... ouais non mais c'est vrai ça énerve, même moi là j'ai envie de...",
                author: "Laurence", scene: 581, difficulty: 2 },
                { quote: "Est-ce que quelqu'un sait ce qu'est un fléau ?",
                author: "Nadine", scene: 582, difficulty: 2 },
                { quote: "Qui a remarqué quelque chose ? Personne n'a rien remarqué ?",
                author: "Nadine", scene: 583, difficulty: 4 },
                { quote: "Bon eh bien, je voulais du fond du cœur m'excuser. Sincèrement. Mes enfants, vous dire combien je vous aime !",
                author: "Nadine", scene: 584, difficulty: 2 },
                { quote: "Parce que je n'étais pas dans mon état... disons normal.",
                author: "Nadine", scene: 585, difficulty: 4 },
                { quote: "Je sais que ça a dû être terrible pour certains. Surtout pour toi, Candy. Charlotte.",
                author: "Nadine", scene: 586, difficulty: 2 },
                { quote: "A cause de ça ! La schnouff ! La schnouff, c'est de la drogue ! Bon, ça reste des plantes.",
                author: "Nadine", scene: 587, difficulty: 2 },
                { quote: "Attention... je compte sur vous pour ne rien dire à vos parents. Surtout toi, Frédéric.",
                author: "Nadine", scene: 588, difficulty: 2 },
                { quote: "Sinon la schnouff ça se fume, et si on combine ça avec de la téquila ou n'importe quel autre alcool fort, on est malade. Très malade.",
                author: "Nadine", scene: 589, difficulty: 2 },
                { quote: "C'est chouette mais ça reste de la drogue.",
                author: "Nadine", scene: 590, difficulty: 4 },
                { quote: "La schnouff, c'est un fléau. Il ne faut jamais, jamais, jamais toucher à ça. Compris ?",
                author: "Nadine", scene: 591, difficulty: 2 },
                { quote: "J'ai jamais rien ressenti de si fort.",
                author: "Stef", scene: 592, difficulty: 4 },
                { quote: "Pendant qu'on faisait l'amour, elle me regardait avec ses grands yeux de labrador.",
                author: "Stef", scene: 593, difficulty: 2 },
                { quote: "Ouais, je vois. C'est pas à un vieux singe qu'on apprend à faire des grimaces, fieu.",
                author: "JC", scene: 594, difficulty: 3 },
                { quote: "Honnêtement, je crois qu'elle a jamais dû être prise comme ça. Je dis pas ça pour me vanter. Après elle a pleuré, c'est pour te dire.",
                author: "Stef", scene: 595, difficulty: 2 },
                { quote: "C'est un classique, ça fieu.",
                author: "JC", scene: 596, difficulty: 4 },
                { quote: "Après tous les problèmes de drogue qu'elle a vécu, ses trucs à trois...",
                author: "Stef", scene: 597, difficulty: 3 },
                { quote: "Tu veux dire, les gang bangs.",
                author: "JC", scene: 598, difficulty: 3 },
                { quote: "T'as fait un sans faute jusqu'au point G.",
                author: "JC", scene: 599, difficulty: 2 },
                { quote: "Oublie quand même pas que c'est grâce à moi.",
                author: "JC", scene: 600, difficulty: 3 },
                { quote: "Ben de rien, fieu. Eh ben c'est bien, ça. Tu vas pouvoir t'acheter un clebs, maintenant.",
                author: "JC", scene: 601, difficulty: 3 },
                { quote: "Il y a qu'à demander. Avec plaisir. J'ai pas mon cutter mais ça va aller.",
                author: "JC", scene: 602, difficulty: 3 },
                { quote: "Mais je préviens tout de suite. Je veux bien éplucher le lapin, mais pas les carottes.",
                author: "JC", scene: 603, difficulty: 2 },
                { quote: "Le plus important, c'est de lui donner un grand coup sur la tête, dans la nuque là, tu vois ? Faut pas hésiter. Comme ça : tac !",
                author: "JC", scene: 604, difficulty: 2 },
                { quote: "Après, t'as plus qu'à lui enlever son petit pyjama, et je peux même te faire une cagoule pour ta gamine.",
                author: "JC", scene: 605, difficulty: 2 },
                { quote: "Que les âmes sensibles ferment les yeux. Adieu petit lapin.",
                author: "JC", scene: 606, difficulty: 2 },
                { quote: "Petite cochonne. T'as peut-être pas de sous mais t'as une belle tirelire.",
                author: "Claudy", scene: 607, difficulty: 3 }
              ].freeze
    end
  end
end
